---
title: "The impact of government responses to COVID-19 on women´s reproductive health"
description: Return to [CoronaNet](https://coronanet-project.org/)
author:
  - name: Ines Böhret 
    url: https://www.linkedin.com/in/ines-boehret/?originalSubdomain=de
    affiliation: University of Manchester
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
body {
text-align: justify}
</style>

*“We have seen how the virus does not discriminate, but its impacts do”* ^[Guterres, A. 2020. “We Are All in This Together: Human Rights and COVID-19 Response and Recovery | United Nations.” Accessed April 28, 2020. https://www.un.org/en/un-coronavirus-communications-team/we-are-all-together-human-rights-and-covid-19-response-and]

Epidemics often have a gendered impact by increasing the vulnerability of women and girls. Yet, in many cases public responses have shown a lack to mitigate these effects and sometimes have even strengthened disparities by adopting discriminating policies. This paper aims to give an overview of the current governmental policies released in response to the COVID-19 pandemic that have a direct or indirect impact on the reproductive rights and health of women. Therefore, the dataset by Coronanet^[Cheng, Cindy, Joan Barcelo, Hartnett, Allison, Robert Kubinec, and Luca Messerschmidt. 2020. “Coronanet: A Dyadic Dataset of Government Responses to the COVID-19 Pandemic: BETA Version 1.0.” Accessed April 22, 2020] was searched for policies referring to reproductive and maternal health. While there have been policies aiming to support and protect pregnant and birthing women, several governmental measures have the potential to increase gender inequalities. It is concluded that in response to the current pandemic women´s rights are being violated and awareness for reproductive health and rights needs to be increased in governmental policies.

Social inequalities shape the impact of disasters and the gendered dimension of diseases can be increased by response measures. The disproportionate effect of epidemics on women has already been discussed regarding previous outbreaks and the need to prevent the violation of women´s rights through disaster responses has been stressed before.^[Smith, Julia. 2019. “Overcoming the ‘Tyranny of the Urgent’: Integrating Gender into Disease Outbreak Preparedness and Response.” Gender & Development 27 (2): 355–69. https://doi.org/10.1080/13552074.2019.1615288;  Davies, S., E., and B. Bennet. 2016. “A Gendered Human Rights Analysis of Ebola and Zika: Locating Gender in Global Health Emergencies.” International Affairs 92 (5): 1041–60.https://doi.org/10.1111/1468-2346.12704] However, the response measures to COVID-19 often neglect the needs and rights of women or indirectly strengthen structures of inequality. For example, the closure of kindergartens and schools have increased the already existing inequalities in the gender division of unpaid labour ^[United Nations, 9. April 2020, https://www.unwomen.org/-/media/headquarters/attachments/sections/library/publications/2020/policy-brief-the-impact-of-covid-19-on-women-en.pdf?la=en&vs=1406 ] and the restrictions of particular services, such as the closing of women´s shelters, have directly increased the vulnerability to violence of many women.^[OHCHR. 2020. “COVID-19 and Women´s Human Rights: Guidance: What Is the Impact of Covid-19 on Gender-Based Violence?” Accessed April 29, 2020. https://www.ohchr.org/Documents/Issues/Women/COVID-19_and_Womens_Human_Rights.pdf.] Thus, governmental responses to COVID-19 have the potential to increase gender-based inequalities. 

There have been a few policies acknowledging reproductive and maternal rights of women next to the biomedical needs of the pandemic, while others severely violate women´s access to health. Some governments have aimed to mitigate gender-based inequalities regarding reproductive and maternal health caused by the responses to COVID-19. For example, in England and Wales home abortions have been made legal and in the Czech Republic as well as in Finland visitor bans in hospitals did not apply to pregnant women.^[Cheng, Cindy, Joan Barcelo, Hartnett, Allison, Robert Kubinec, and Luca Messerschmidt. 2020. “Coronanet: A Dyadic Dataset of Government Responses to the COVID-19 Pandemic: BETA Version 1.0.” Accessed April 22, 2020.] Yet, many policies seem to intentionally and unintentionally interfere with the right to reproductive and maternal health. The next paragraphs focus on some of these policies targeting reproductive rights, antenatal care and birthing rights. 

Previous epidemics have shown how reproductive rights are politized in times of emergency.^[Davies, S., E., and B. Bennet. 2016. “A Gendered Human Rights Analysis of Ebola and Zika: Locating Gender in Global Health Emergencies.” International Affairs 92 (5): 1041–60.https://doi.org/10.1111/1468-2346.12704.] During the current response to COVID-19 there have been measures leading indirectly to reducing access to reproductive health as well as direct impacts. For example, in some US states abortions have been restricted or banned as “non-essential medical procedures”,^[Abrams, A. 2020. “COVID-19 Could Permanently Make Abortions Harder to Access Nationwide.” Time, April 7. Accessed April 29, 2020. https://www.unfpa.org/sites/default/files/resource-pdf/COVID-19_Update_No-2_UNFPA_Supplies_v5.pdf] while shutdowns of manufacturers and lockdowns in many states have led to restricted access to contraception.^[United Nations. 2020. “Policy Brief: The Impact of COVID-19 on Women.” Accessed April 29, 2020. https://www.ohchr.org/Documents/Issues/Women/COVID-19_and_Womens_Human_Rights.pdf.  and UNFPA, 30. March 2020, https://www.unfpa.org/resources/unfpa-supplies-covid-19-update-30-march-2020 ] Such policies are thought to contribute to about 7 million unintended pregnancies^[UN News. 2020. “COVID-19 Could Lead to Millions of Unintended Pregnancies, New UN-Backed Data Reveals.” Accessed April 29, 2020. https://journals.plos.org/plosone/article/file?type=printable&id=10.1371/journal.pone.0165621.] which in turn do not only have an impact on the socioeconomic situation of women but are also a risk factor for maternal mortality.^[Hall, Jennifer Anne, Geraldine Barrett, Tambosi Phiri, Andrew Copas, Address Malata, and Judith Stephenson. 2016. “Prevalence and Determinants of Unintended Pregnancy in Mchinji District, Malawi; Using a Conceptual Hierarchy to Inform Analysis.” PloS one 11 (10): e0165621.https://doi.org/10.1371/journal.pone.0165621] 

In addition, policies have been negatively influencing maternity care. The organization Human Rights in Childbirth has documented restrictions of maternal rights during the COVID-19 pandemic including the de-prioritisation and closure of maternity services, denial of birth companion and obstetric violence.^[Drandić, D. 2020. “HRiC Informs European Parliament Action on Maternity Care During COVID-19.” Accessed April 24, 2020. http://humanrightsinchildbirth.org/index.php/2020/04/23/hric-informs-european-parliament-action-on-maternity-care-during-covid-19/.] This dataset shows that on the national level there have been at least four policies on four continents turning maternity units or women´s hospitals into COVID-19 treatment centres.^[Cheng, Cindy, Joan Barcelo, Hartnett, Allison, Robert Kubinec, and Luca Messerschmidt. 2020. “Coronanet: A Dyadic Dataset of Government Responses to the COVID-19 Pandemic: BETA Version 1.0.” Accessed April 22, 2020.] In Angola, Brazil, Myanmar and Russia health care institutions originally dedicated to support women´s health, have been used for patients infected with COVID-19 and it stays unclear to which extend these limitations in maternal health services have been compensated. However, such measures likely put an additional pressure on staff and resources and thereby increase the risk for restricted care and obstetric violence.^[Rocca-Ihenacho, Lucia, and Cristina Alonso. 2020. “Where Do Women Birth During a Pandemic? Changing Perspectives on Safe Motherhood During the COVID-19 Pandemic.” J Glob Health Sci 2.https://doi.org/10.35500/jghs.2020.2.e4]  

Furthermore, restrictive policies have directly targeted pregnant women and birthing rights have been denied despite the WHO-guidance.^[WHO. 2020. “Pregnancy, Childbirth, Breastfeeding and COVID-19.” Accessed April 23, 2020. https://www.who.int/reproductivehealth/publications/emergencies/COVID-19-pregnancy-ipc-breastfeeding-infographics/en/.] Access to consultations and antenatal care has been restricted or forbidden and women in labour have been denied birth companions. Bulgaria, for example, has suspended consultations for pregnant women and in Guatemala pregnant women have not been allowed to leave their homes.^[Cheng, Cindy, Joan Barcelo, Hartnett, Allison, Robert Kubinec, and Luca Messerschmidt. 2020. “Coronanet: A Dyadic Dataset of Government Responses to the COVID-19 Pandemic: BETA Version 1.0.” Accessed April 22, 2020.] Also, various countries applied visitor bans for hospitals and clinics without making exceptions for birth companions such as partners and doulas.^[Ibdm.] These restrictions have direct and indirect detrimental effects on the antenatal, perinatal, and postpartum health of women by limiting support and care while increasing levels of stress and anxiousness through isolation and uncertainty.^[Oja, L. 2020. “Sexual and Reproductive Rights in Time of the Covid-19 Pandemic: Reflections and Notes.” Accessed April 23, 2020. https://www.liirioja.com/srhr-writings] 

In conclusion, it is evident that there are number of current governmental responses to COVID-19 that strengthen gender inequalities and compromise women´s rights to reproductive and maternal health. De-prioritization of health care services next to direct violations of women´s reproductive rights might have detrimental long-term effects. Zampas^[Zampas, C. 2020. “Covid 19: A Wake-up Call to Eliminate Barriers to SRHR.” Sexual and Reproductive Health Matters.http://www.srhm.org/news/covid-19-a-wake-up-call-to-eliminate-barriers-to-srhr/. Accessed April 23, 2020.] rightly highlights that such barriers to sexual and reproductive health have always existed for marginalized people and this might be the first time that women from all economic and ethnic backgrounds share the negative impact of an epidemic based on their gender. While devastating, this could be a chance for a shift towards a more gender-sensitive disaster response in the future through a shared awareness for reproductive and maternal rights.
