---
title: "The Flaw in Indonesia’s Large-Scale Social Restrictions Policy"
description: Return to [CoronaNet](https://coronanet-project.org/)
author:
  - name: Fadhilah Fitri Primandari 
    url: https://www.linkedin.com/in/fadhilah-fitri-primandari/?originalSubdomain=id
    affiliation: Universitas Indonesia
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
body {
text-align: justify}
</style>

As predicted, the number of Covid-19 cases in Indonesia has continued to rise. As of April 13, the country has seen 4,557 confirmed cases, with 399 deaths.^[Worldometer – Indonesia. April 13th, 2020. Worldometer. https://www.worldometers.info/coronavirus/country/indonesia/]  Jakarta, Indonesia’s capital, has seen 4,377 burials in March alone ^[  Allard, Tom; Kapoor, Kanupriya; & Widianto, Stanley. April 4th, 2020. Reuters. https://www.reuters.com/article/us-health-coronavirus-indonesia-funerals/exclusive-jump-in-jakarta-funerals-raises-fears-of-unreported-coronavirus-deaths-idUSKBN21L2XU] —40% higher than any month in the past year—while as of April 7, at least 639 were handled by following the Covid-19 protocol, ^[Nurbaiti, Alya. April 7th, 2020. The Jakarta Post. https://www.thejakartapost.com/news/2020/04/07/jakarta-buries-639-bodies-according-to-covid-19-protocols.html] indicating a large number of undetected infections. On March 31, the central government passed a government regulation on large-scale social restrictions which allows regions to close schools and workplaces, limit activities in public spaces, as well as restrict inbound and outbound travels. At first glance, this policy seemed like a big step by the government towards a more rigorous framework to combat the outbreak, especially after weeks of public criticism. However, if we look closer, it does not seem that this new policy is sufficient to address the ongoing country’s health crisis. 

With the country’s alarming increase in cases as well as its limited health infrastructure capacity ^[For further details, see Shidiq, Akhmad Rizal. April 8th, 2020. Centre of Strategic and International Studies Indonesia. https://csis.or.id/publications/our-health-system-capacity-vs-the-demand-from-a-large-scale-social-distancing-policy ] and lack of sufficient protective equipment for medical professionals, ^[CNN Indonesia. April 8th, 2020. https://www.cnnindonesia.com/nasional/20200408095145-20-491503/darurat-corona-tito-akui-masih-ada-daerah-kekurangan-apd] it only makes sense for the Indonesian government to employ a preventive approach in its fights against the outbreak. As of June 2019, Indonesia’s doctor to population ratio is one to 2,000; ^[ Petriella, Yanita. June 20th, 2019. Bisnis Indonesia. https://ekonomi.bisnis.com/read/20190620/12/935811/indonesia-kebanyakan-dokter-tetapi-terpusat-di-kota-besar ] this number is half of WHO’s standard recommendation of one to 1,000. Meanwhile, at least 32 doctors have died due to their exposure to the coronavirus as of April 12. ^[Setyowati, Desy. April 12th, 2020. Katadata. https://katadata.co.id/berita/2020/04/12/44-dokter-dan-perawat-ri-meninggal-dunia-akibat-virus-corona ] The majority of them served in Jakarta, indicating a strain even in the country’s capital. This makes the call for a preventive approach more urgent. 

In contrast to this need, the regulation for large-scale social restrictions is corrective and optional. The policy prescribes that regional administrations wishing to apply the policy in their regions should be able to show significant number of cases or deaths and local transmission rates in order to obtain approval from the health minister. It is unclear what ‘significant’ means or what the threshold is for the health minister to consider large-scale social restrictions appropriate for a certain region. As of April 12, the health minister has approved the policy for Jakarta and five of its satellite municipalities—the regency and city of Bogor, the regency and city of Bekasi, and Depok. It is expected that the area would pass for the policy, as it has been an epicenter for the virus. Jakarta alone has seen 2,242 confirmed cases as of April 13, ^[Provincial Government of DKI Jakarta. April 14th, 2020. https://corona.jakarta.go.id/id/data] making up almost half of the country’s total confirmed cases. The concern is whether other regions that are yet to report a surge in their number of cases would be eligible. The current developments don’t seem favorable, as on April 12, the health minister rejected the proposals from Rote Ndao, Mimika, Fakfak, Sorong, and Palangkaraya on the grounds that they have not seen significant numbers of cases and transmission rates. ^[ Rozie, Fachrur. April 12th, 2020. Liputan6. https://www.liputan6.com/news/read/4225630/menkes-tolak-pengajuan-psbb-corona-sejumlah-daerah-ini-daftarnya ] 

Indonesia has already lagged behind in its conduct of testing for the virus, ^[Lindsey, Tim & Mann, Tim. April 8th, 2020. ABC News. https://www.abc.net.au/news/2020-04-08/coronavirus-could-cause-240,000-deaths-in-indonesia/12131778] which has drawn concerns for widespread but undetected cases, especially in regions far from the capital. Meanwhile, the past two weeks have seen high numbers of people leaving Jakarta, as many workplaces have closed and people feared the probability of a lockdown. ^[For further details, see Asmara, Chandra Gian. March 30th, 2020. CNBC Indonesia. https://www.cnbcindonesia.com/news/20200330121333-4-148434/jokowi-sebut-14000-orang-mudik-awas-corona-menyebar and Okthariza, Noory. April 9th 2020. Centre of Strategic and International Studies Indonesia. https://www.csis.or.id/publications/pergerakan-orang-di-jakarta-saat-pandemi-covid-19-analisis-data-facebook-disease-prevention-map] Transmissions of the virus to other regions are likely to be high, and stringent measures to anticipate them should not wait for the use of test kits to confirm them.  

Indonesia needs to stop using ad hoc approaches in dealing with its problems, especially on issues with high risks of escalation. Waiting for harms to happen, particularly in the case of the coronavirus, would mean waiting for more people to get sick or worse, die. While policies should be based on evidence instead of speculations, the already rising number of cases in the country as well as the trends faced by other countries should be enough evidence that many Indonesians are at risk of contracting the virus. The Indonesian government should also keep in mind that, in addition to its already strained health infrastructure, regions far from the capital—especially outside Java—have fewer medical professionals. ^[For statistics of the distribution, see Lokadata. 2017. https://lokadata.beritagar.id/chart/preview/sebaran-dokter-menurut-provinsi-2017-1540356601] These regions may face the brunt if they need to wait for surges in their number of confirmed cases. 

In addition to dropping this ad hoc approach, the Indonesian government should be more rigorous in encouraging regions to consider implementing the large-scale social restrictions policy, especially those that have seen inbound travel from the capital and are able to project their economic capacity in enforcing the policy. Having experienced spikes of cases after weeks of downplaying the risks of the virus—followed by the rush and struggle to make amends—Indonesia should not wait for another round of escalation. A study by the Faculty of Public Health at Universitas Indonesia shows that without government intervention, Indonesia may see as many as 2.5 million cases and 240,244 deaths by the 77th day since its first case. ^[Nafi, Muchamad. April 6th, 2020. Katadata. https://katadata.co.id/berita/2020/04/06/gelombang-virus-corona-di-antara-minimnya-fasilitas-dan-tenaga-medis] With this prediction in mind, it is reckless to opt for a corrective approach—especially without having actual corrective capacity. 


  
  


