---
title: "Honduras Country Report"
description: Return to [CoronaNet](https://coronanet-project.org/)
author:
  - name: Nicole Oubre
    url: https://www.linkedin.com/in/nicole-oubre-427790189/
    affiliation: Willy Brandt School of Public Policy
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
body {
text-align: justify}
</style>

Honduras is located in Central America with a population of approximately 9.6 million. The country has taken strict measures to reduce COVID-19 infections which are taking a toll on an already struggling country.

Healthcare 
Honduras’ health care system has been described as one of the worst in Central America, with poor investment. Hospitals and health centers suffer from weak infrastructure and a critical shortage of beds. There are only 0.4 hospitals per 100,000 inhabitants, one of the worst in Central America, second only to Guatemala. The country has approximately 9.5 hospital beds per 10,000 inhabitants, for a total of 6,590 beds.^[Fiallos, Signey. May, 2019. Centro de estudio para la Democracia. http://cespad.org.hn/wp-content/uploads/2019/05/Profundidad9-OSF.pdf] These numbers reveal the threat COVID-19 presents for Honduras and its failing healthcare system. The head of the Medical Association of the Honduran Social Security Institute (IHSS), Carlos Umaña, expects that once Honduras reaches 1,000 coronavirus cases, which it did by May 5th, the collapse of the healthcare system will be imminent.^[El Heraldo. May 2, 2020. https://www.elheraldo.hn/pais/1376901-466/colapso-hospitalario-es-inminente-en-una-etapa-exponencial-del-covid-19]

Since the first reported case appeared in the country on March 11th, confirmed cases and deaths continue to rise. As of May 24th, there are 3,743 confirmed cases and 174 deaths.^[Gobierno de la República de Honduras. May 24, 2020. Sistema Nacional de Gestión de Riesgo (SINAGER). http://www.trabajo.gob.hn/266-casos-de-covid-19-confirmados/] The first two cases originated from two women who had recently arrived in Honduras from Spain and Switzerland. While Honduras is reporting a relatively low number of COVID-19 infections, only 7,105 tests have been administered, well below other Central American countries.^[Sosa, Eugenio. May 12, 2020. Centro de estudio para la Democracia. https://cespad.org.hn/2020/05/13/analisis-la-gestion-politica-de-la-pandemia-en-honduras-hacia-donde-vamos/#_ftnref1]

In April, 10% of people officially diagnosed with COVID-19 died, one of the highest fatality rates in Latin America. However, in May, the fatality rate improved with less than 5% of cases resulting in death. Improvements are thought to be attributed to a change in strategy that emphasizes early treatment to reduce the need for intensive care.^[Díaz, Marco Gonzáles. May 22, 2020. BBC. https://www.bbc.com/mundo/noticias-america-latina-52749761]

Prevention Measures
On March 16th, the Honduran President Juan Orlando Hernández announced a nationwide curfew and an absolute curfew in the cities of the Central District, La Ceiba, and Choluteca. Throughout Honduras, people are required to stay home except for going to supermarkets, pharmacies, hospitals, gas stations, and essential places of work from 7:00 am-5:00 pm. The days they are allowed to circulate is dependent on the last digit of their ID number. For example, numbers ending in 1 or 2 can only go out on Mondays, and numbers ending in 3 or 4 can only go out on Tuesdays. In the Central District, La Ceiba, and Choluteca these exceptions do not apply. Entrance to these cities and any circulation within them is prohibited. The national curfew has since been extended until May 24th. Cities that are on absolute curfew have shifted based on the rate of infection. 

Since April 7th, Hondurans are required to wear a mask when outside the home. To achieve this goal, the Honduran Ministry of Health aims to deliver a mask to each person in Honduras. By April 15th, 30,000 masks have been delivered, with numbers increasing every week.^[COVID 19 Honduras. May 6, 2020. Despacho de comunicaciones y estrategia presidencia. https://covid19honduras.org/?q=node/369] On May 19th, The National Congress passed the Mandatory Use of Masks and the Application of Biosafety Protocols law, which requires mask-wearing in public, and in private when more than five people are present. 

Despite the rejection from Honduras, Mexico deported approximately 400 Honduran nationals. In response, Honduras set up 4 temporary isolation centers where deportees from Mexico and the United States were quarantined for 14 days.^[COVID 19 Honduras. May 6, 2020. Despacho de comunicaciones y estrategia presidencia. https://covid19honduras.org/?q=node/370]

Economic Impact
Honduras’ economy has had the second-highest growth rate in Central America in recent years. However, due to COVID-19, the World Bank estimates that Honduras’ economy will contract by 2.3% by the end of 2020 and 3.9% in 2021.^[World Bank. April 12, 2020. https://www.worldbank.org/en/country/honduras/overview] In a country where 48.3% of the population live in poverty, a recession will be devastating. In an attempt to avoid the economic downfall, the government of Honduras has taken several measures. The government authorized the issuance of debt up to $2.5 billion, delayed income tax payments for micro, small, and medium-sized business employees^[Americas Society/Council of the Americas. N.d. https://www.as-coa.org/articles/where-coronavirus-latin-america#honduras], and implemented price freezes on 30 essential grocery items.^[La Presna. April 25, 2020. https://www.laprensa.hn/honduras/1375277-410/congelan-precios-canasta-basica-secretaria-desarrollo-toque-queda] 

Enforcement
The National Police and Armed Forces have been tasked to enforce policies related to CODIV-19 preventive measures. Failure to comply with the measures have been met with legal consequences. The curfew is strictly enforced, with arrests being reported across the media. As of April 9th, 6,000 people have been arrested throughout the country for not complying with the curfew.^[Agencia EFE. April 9, 2020. https://www.efe.com/efe/america/sociedad/mas-de-6-000-detenidos-en-honduras-por-incumplir-el-toque-queda-covid-19/20000013-4217796] Additionally, 2,000 vehicles have been seized^[Agencia EFE. April 9, 2020. https://www.efe.com/efe/america/sociedad/mas-de-6-000-detenidos-en-honduras-por-incumplir-el-toque-queda-covid-19/20000013-4217796] and 350 drivers licenses confiscated.^[La Presna. March 23, 2020. https://www.laprensa.hn/sucesos/1366376-410/detenidos-toque-queda-coronavirus-covid-cuarentena-honduras] Arrests have also been made concerning bars and restaurants that were supposed to be closed.^[La Presna. March 16, 2020. https://www.laprensa.hn/honduras/1364626-410/honduras-toque-queda-absoluto-coronavirus]

Outlook
Honduras began reopening after May 4th, when Honduras’ Labor Secretary published detailed biosafety protocols^[Secretary of Labor and Social Security. May 4, 2020. http://www.trabajo.gob.hn/protocolos-de-bioseguridad-en-los-centros-de-trabajo/] for industries to reopen safely. The Secretary warned that the protocols are mandatory, and failure to comply would result in business closures.^[ Heraldo. April 28, 2020. https://www.elheraldo.hn/pais/1375900-466/secretar%C3%ADa-de-trabajo-elabora-protocolo-para-reabrir-empresas ] Since the announcement, the construction sector has resumed and expects to see more than 250,000 employees gradually return to work.^[Rivera, Juan Carlos. May 10, 2020. La Presna. https://www.laprensa.hn/honduras/1378842-410/construccion-inicia-reactivacion-inteligente-covid-honduras] The manufacturing sector is also set to resume on May 18th, with 10-15% of companies returning to work each week.^[La Presna. May 10, 2020. https://www.laprensa.hn/honduras/1378868-410/maquilas-trabajar-18-mayo-coronavirus-honduras] Restaurants and hair salons/barbershops have also begun reopening their doors. Other sectors are expected to follow suit in hopes of stimulating Honduras’ economy.