---
title: "Country Report | COVID-19 Infection Control in Syria: The Necessity of Transparency"
description: Return to [CoronaNet](https://coronanet-project.org/)
author:
  - name: Lily Zandstra 
    url: https://www.linkedin.com/in/lily-zandstra-242967158/?originalSubdomain=nl
    affiliation: 
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
body {
text-align: justify}
</style>

Fear looms amongst the Syrian people as COVID-19 threatens the war-torn region, which has precious few means to prevent, diagnose and treat an outbreak. With six and a half million displaced people residing in overcrowded camps and 85% of the population living below the poverty line, a nationwide epidemic would be harrowing.^[Antaki, Nabil. April 24th, 2020. French RT.] The Syrian Health Ministry recorded on April 21 that there are 43 coronavirus infections, 19 people have recovered, and three deaths have been recorded.^[Sabbagh, Hazem. April 28nd, 2020. Syrian Arab News Agency. https://sana.sy/en/?p=190575
] A COVID-19 outbreak in Syria seems inescapable. Its high poverty rate, lack of resources and nine years of conflict expose the country as particularly vulnerable to the virus. However, the lack of transparency is further contributing to unforgiving transmission. Greater international initiatives on how to fight off the pandemic in conflict-ridden cases such as Syria are urgent.

My own research on the various government responses to the coronavirus has revealed that transparency is a critical factor for the effective management of COVID-19. Syria is certainly not the first to be accused of downplaying information during a national crisis, however, due to its limited resource capacity and, therefore, its reliance on strong preventative mechanisms to counter the spread of COVID-19, greater levels of transparency are needed. Transparency has to do with the dissemination of quality information and the building of trust- prerequisites for effective policy responses. Transparency is particularly necessary in cases such as Syria, both at a national and international level. Accurate information concerning the disease is needed for useful guidelines to be adopted. A policy response should be based on factual evidence and comprehensible for the general public. However, transparency also has to do with the promotion of trust between the public and the authorities, presented in a stimulating manner in order for people to adopt the necessary practices.^[O'Malley, Peter, John Rainford, and Alison Thompson. April 21st, 2020. Bulletin of the World Health Organization 87] The Syrian people risk catastrophic exposure to the virus as Syria’s lack of transparency concerning the number of infected cases leaves the healthcare system defenceless.

The Syrian government faced stark criticism about their downplaying on the number of infected cases of COVID-19.^[Moubayed, Sami. April 24th 2020. Gulf News. https://gulfnews.com/world/mena/has-the-coronavirus-reached-syria-1.70539898] On March 10 the Syrian Observatory for Human Rights  reported COVID-19 cases in Tartous, Damascus, Homs and Latakia.^[Cited in Petkova, Mariya. April 18th 2020. Aljazeera. https://www.aljazeera.com/news/2020/03/concern-mounts-catastrophic-coronavirus-outbreak-syria-200316003354976.html] The Syrian government manifested that the virus had not spread in these areas under its control. However, Syria’s infection rates seem dubiously low compared to its neighbouring countries. Iran, for example, has witnessed a severe growth of infected cases and has close relations with Syria. Syria hosts thousands of military forces and receives approximately 22,000 religious tourists from Iran each year.^[Gharibah, Mazen, and Zaki Mehchy. April 27th 2020. LSE Research Online. http://eprints.lse.ac.uk/103841/1/CRP_covid_19_in_Syria_policy_memo_published.pdf?fbclid=IwAR0-7fK6LGG9Y9jokt6XdM3Yxvubh4IFvcrmqZ4RM5JNIQALs7kvJT3qw70] 

On March 14, the education minister Imad al-Azab closed all schools and universities until April 2.^[ Knecht, Eric. April 18th, 2020. Reuters. https://www.reuters.com/article/us-health-coronavirus-syria/syria-insisting-it-is-coronavirus-free-takes-broad-steps-to-prevent-spread-idUSKBN2110SA] The Ministry of Religious Endowments also shut down all directorates and divisions, and for two weeks Friday prayers and group prayers were suspended. In addition, the parliamentary elections were postponed until May 20, and non-essential shops, restaurants, cafes, sports clubs and places of public entertainment were abruptly closed.^[Al-Khateb, Khaled. April 18th, 2020. Al monitor. https://www.al-monitor.com/pulse/originals/2020/03/syria-coronavirus-who-pandemic-denial-cases-detention-camps.html] The sterilization and disinfection of the cities was another preventative measure taken, and the disinfection of vehicles entering the City of Aleppo became a common sight.^[Syrian Arab News Agency. April 18th, 2020. https://sana.sy/en/?p=189486] The suspension of drivers licenses and military service completion were further measures.^[ Manar Hamigo, Muhammad. April 18th, 2020. Alwatonline. https://www.alwatanonline.com/%D8%A7%D9%84%D8%AA%D8%AC%D9%86%D9%8A%D8%AF-%D8%A7%D9%84%D8%B9%D8%A7%D9%85%D8%A9-%D8%AA%D8%A4%D8%AC%D9%91%D9%84-%D8%A7%D9%84%D8%B3%D9%88%D9%82-%D9%88%D9%85%D9%86%D8%AD-%D8%AF%D9%81%D8%A7/] On March 23 the government recorded its first case of COVID-19. The Minister of Health, Dr Nizar Yazigi, conveyed on state television that the person infected was a 20-year-old who had come from abroad. This message conveyed that precautionary measures were taken effectively and appropriately, as the patient was quarantined upon her arrival, despite showing no symptoms.^[Al-Khateb, Khaled. April 18th, 2020. Al monitor. https://www.al-monitor.com/pulse/originals/2020/03/syria-coronavirus-who-pandemic-denial-cases-detention-camps.html] The initial voluntary precautionary measures were heightened later in March as travel restrictions were placed, restricting the movement of citizens between provinces. A night curfew from 6 pm-6 am was also introduced. So far, the Syrian people appear to remain oblivious to the detriments of the pandemic as people attend religious gatherings and market places bustle. “Great levels of fear” among the Syrian people have, however, also been reported as some anticipate that the government is not reporting all infections for political purposes leaving them with little knowledge on how to safeguard themselves against the virus.^[Petkova, Mariya. April 18th 2020. Aljazeera. https://www.aljazeera.com/news/2020/03/concern-mounts-catastrophic-coronavirus-outbreak-syria-200316003354976.html] Yet, these fears do not stem from the management of the virus itself but from perceiving the pandemic as a security threat. It has been reported that the military intelligence agency has arranged funerals. A public awareness campaign was further precluded from distributing flyers by intelligence officers. The government risks the good health of its people if it continues to bury stories in order to avert revolt.^[Gharibah, Mazen, and Zaki Mehchy. April 27th 2020. LSE Research Online. http://eprints.lse.ac.uk/103841/1/CRP_covid_19_in_Syria_policy_memo_published.pdf?fbclid=IwAR0-7fK6LGG9Y9jokt6XdM3Yxvubh4IFvcrmqZ4RM5JNIQALs7kvJT3qw70] 

Syria’s transparency deficit creates increasing uncertainty about how such a frail healthcare system can cope with the coronavirus. The medical resources needed to diagnose and treat the virus are simply insufficient. A doctor in the Aleppo region shed light on the testing capacity. Describing how they have no means to test patients as all suspected cases are sent to the central laboratory in Damascus but that he suspects that patients who had previously suffered from lung disease may have been infected with COVID-19. Moreover, 70% of healthcare workers have fled the country since the conflict began. He gave a hypothetical example of how a city such as Aleppo with a population of 2 million people could deal with a COVID-19 outbreak. He anticipated that if a thousand were infected and one hundred required intensive care, there simply would not be enough respirators.^[Antaki, Nabil. April 24th, 2020. French RT.] The cost of the coronavirus tests have also been reported as they are higher than peoples monthly salaries. In some incidences, tests are being distributed based on personal connections.^[Gharibah, Mazen, and Zaki Mehchy. April 27th 2020. LSE Research Online. http://eprints.lse.ac.uk/103841/1/CRP_covid_19_in_Syria_policy_memo_published.pdf?fbclid=IwAR0-7fK6LGG9Y9jokt6XdM3Yxvubh4IFvcrmqZ4RM5JNIQALs7kvJT3qw70] Transparency is a critical tool needed to control the outbreak, by, for instance, allocating limited resources more equitably.^[O'Malley, Peter, John Rainford, and Alison Thompson. April 21st, 2020. Bulletin of the World Health Organization 87] Covering up the number of infected cases has prevented practical response mechanisms.

The case in Syria is poignant. Preventive, diagnostic and treatment measures seem feeble as the country's only viable measures to handle the outbreak; infection control has been further hindered by the governments’ lack of transparent communication. To date, the number of reported infected COVID-19 cases in Syria is under suspicion. If we are to endure this pandemic globally is it incumbent upon the international community to support Syria. The urgent priority is how greater transparency can be promoted and incorporated in response plans as the international community deals with COVID-19 in conflict settings. 



