---
title: "Research Report on Eswatini"
description: Return to [CoronaNet](https://coronanet-project.org/)
author:
  - name: Laurent Frick 
    affiliation: University of Innsbruck
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
body {
text-align: justify}
</style>

## Country Report: Eswatini {-}
Eswatini is a small country with about 1.2 million inhabitants, which is like many countries in theworld affected by the coronavirus-pandemic. The form of the government is an unitaryparliamentary absolute monarchy, which means that the present king, Mswati III, is the chief of the state and every policy the parliamentary government is enforcing must be signed by him. 

All thelaw regulations in response to coronavirus-pandemic are implemented on the national level. At the beginning of March, Eswatini's national government reported the first person diagnozed with COVID-19. This case was followed by a declaration of national emergency on March 17th with the first regulations in order to prevent spreading the virus in the country. The first legal step was an introduction of social distancing and travel restrictions. On March 24th, the national government announced a partial lockdown for the whole country. On the 16th of April 2020, there were 17 confirmed cases of positive tested people, 1 person was announced to have died because of COVID-19. The national government of Eswatini was mostly following the worldwide standard procedures in response to coronavirus-pandemic. The database for a scientific research on Eswatini's policies combating the coronavirus-pandemic is quite narrow because local media are only quoting the official press statements of the national government. Beside the national government, there are no other official authorities which enforce policies in response to coronavirus-pandemic.



  
  


