---
title: "Myanmar Country Report"
description: Return to [CoronaNet](https://coronanet-project.org/)
author:
  - name: Cara Kim 
    url: 
    affiliation: Technical University of Munich
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
body {
text-align: justify}
</style>

“Until now, no one in our country is infected with COVID-19.”^[Holpuch, Amanda. March 17, 2020. The Guardian. https://www.theguardian.com/world/2020/mar/17/myanmar-has-zero-coronavirus-cases-claims-leader-suu-kyi] This was proclaimed by Myanmar’s state counsellor, Nobel laureate Aung San Suu Kyi, on March 16th. That was when the World Health Organization (WHO) had already declared a pandemic, neighboring China was suffering devastating losses, and European countries were closing their borders and enforcing lockdowns. The government attributed this “luck” to people’s “lifestyle and diet”, that was protecting them from the disease; as well as the use of cash instead of credit cards, which had supposedly helped in curbing the spread of the disease.^[Robertson, Phil. March 17, 2020. Human Rights Watch. https://www.hrw.org/news/2020/03/17/myanmar-denials-define-covid-19-response]

As of June 4th, Myanmar has reported only 236 cases of COVID-19, with 6 deaths.^[Ministry of Health and Sports Myanmar. May 13, 2020. https://doph.maps.arcgis.com/apps/opsdashboard/index.html#/f8fb4ccc3d2d42c7ab0590dbb3fc26b8/] While these numbers suggest that the outbreak is under control, the country's testing capacities reveal a different reality. In February, tests had to be sent to the WHO reference lab in Thailand because Myanmar was not able to perform its tests.^[Nyein, Nyein. April 3, 2020. The Irrawaddy. https://www.irrawaddy.com/specials/myanmar-covid-19/myanmar-run-1000-covid-19-tests-20-turned-positive.html] In April, donated testing machines and kits enabled Myanmar to be able to start testing its own samples, at a rate of 600 per day.^[Angel, Hmue. April 5, 2020. The Myanmar Times. https://www.mmtimes.com/news/myanmar-testing-capacity-covid-19-doubles-600-people-daily.html] To date, around 31,000 people have been tested, far from enough to grasp the full extent of the situation. “You can’t find things you don’t look for”^[Barron, Laignee. February 28, 2020. Time. https://time.com/5792180/southeast-asia-undetected-coronavirus/], as a Harvard epidemiologist said. This lack of wide-scale testing is likely to increase undetected transmission in the country. 

Additionally, Myanmar has a fragile and underdeveloped healthcare system. In 2014, Myanmar spent 2.3%^[World Health Organization. https://www.who.int/countries/mmr/en/] of its GDP on healthcare (OECD average 8.8% of GDP).^[OECD. February 2020 https://www.oecd.org/els/health-systems/health-expenditure.htm] In 2012, Myanmar had 0.9 hospital beds per 1,000 people, in comparison to the world average of 2.7.^[The World Bank. https://data.worldbank.org/indicator/SH.MED.BEDS.ZS] The country is ill-equipped to face a largescale virus outbreak and could suffer from a catastrophe Italy-scale crisis. The government has made efforts to ramp up the country’s healthcare resources by cooperating with the military, building a new hospital, and preparing facilities for quarantine purposes. These efforts were supported by a $50 million credit from the World Bank as part of a global emergency response project to ramp up hospital capacities.^[The World Bank. April 20, 2020. https://www.worldbank.org/en/news/press-release/2020/04/20/myanmar-50-million-in-fast-track-financing-for-national-covid-19-coronavirus-emergency-response]

Before Myanmar reported its first domestic case on March 23rd^[Fullick, Neil. March 24. Reuters. https://www.reuters.com/article/us-health-coronavirus-myanmar/myanmar-reports-first-cases-of-coronavirus-idUSKBN21B0HB], the government had implemented some travel restrictions, prepared facilities for quarantine purposes, and called off the country's largest national holiday. Since the end of March, after the borders were officially closed, many regional and provincial governments started enforcing stricter social distancing measures, such as curfews, stay-at-home-orders, and semi-lockdowns. Beginning in May, the government has shifted its focus towards strict mask-wearing policies while cities and towns slowly reopen. Enforcement of these policies has differed greatly, with offenders being punished unequally, with some facing prison sentences and others being subjected to fines.^[Mann, Zarni. May 13, 2020. The Irrawaddy. https://www.irrawaddy.com/specials/myanmar-covid-19/different-laws-applied-myanmar-covid-19-restrictions-lead-inconsistent-punishments-violators.htm] While these actions are justified through the Prevention and Control of Communicable Disease Law as well as the Natural Disaster Management Law, these seemingly arbitrary decisions further undermine citizen’s need for a system with clear and justified rules and consequences.  

Myanmar faces considerable challenges based on the country's geographic proximity to China. The country shares a 1,348-mile border with China; its biggest investor and most important foreign partner. One of the biggest challenges Myanmar is facing is the return of tens of thousands of migrant workers from Thailand and China after losing their jobs.^[Htwe, Zaw Zaw. April 30, 2020. The Irrawaddy. https://www.irrawaddy.com/specials/myanmar-covid-19/myanmar-migrants-return-thailand-delayed-travel-hassles.html] These circumstances have placed major financial burdens on these people and have left thousands stranded at the border in unsanitary conditions. The return of migrant workers was delayed due to government discussions regarding travel restrictions and the arrangement of necessary quarantine measures. To lower the risk of these workers returning to the country with the virus, they were brought to makeshift government facilities. The workers were quarantined for 21 days before being allowed to return home^[Mann, Zarni. April 20, 2020. The Irrawaddy. https://www.irrawaddy.com/specials/myanmar-covid-19/thousands-myanmar-migrant-workers-return-china-quarantine.html], where they were subject to an additional 7 days of quarantine.^[Htwe, Nyein Ei Ei. April 11, 2020. The Myanmar Times. https://www.mmtimes.com/news/quarantine-period-increased-21-commercial-flight-arrivals-suspended-until-april-30-dassk.html]

COVID-19 is not the only battle that Myanmar is fighting. Violent ethnic conflicts rage in the country, resulting in a humanitarian crisis that has left 240,000^[United Nations Office for the Coordination of Humanitarian Affairs. May 13, 2020. https://www.unocha.org/myanmar] internally displaced persons in camps with low hygiene standards that have been described as “tinderboxes” for COVID-19.^[Human Rights Watch. April 30, 2020. https://www.hrw.org/news/2020/03/30/myanmar-displacement-camps-are-covid-19-tinderboxes] The government’s attempts to supply these camps with healthcare resources are insufficient to protect these vulnerable groups. Moreover, internet blackouts^[Nachemson, Andrew. May 1, 2020. Foreign Policy. https://foreignpolicy.com/2020/05/01/myanmar-coronavirus-pandemic-gives-nationalists-opening-ethnic-minorities-risk/] in these camps are preventing civilians from receiving vital information related to the virus. However, calls for a ceasefire were finally heard as the military declared a limited ceasefire on May 8th.^[China Global Television Network. May 10, 2020. https://news.cgtn.com/news/2020-05-10/Myanmar-military-declares-ceasefire-for-COVID-19-fight-QngnEOEII8/index.html] This came after many resources were allocated to military offensive attacks instead of virus prevention.^[Carter, Leah. May 7, 2020. DW. https://www.dw.com/en/myanmar-armed-conflict-puts-brakes-on-covid-19-response/a-53360164]

As a country that is undergoing a hesitant transition to democracy, Myanmar maintains a tight grip on political and press freedoms. During COVID-19, the country shut down 221 websites^[Chau, Thompson. March 31, 2020. The Myanmar Times. https://www.mmtimes.com/news/telenor-follows-myanmar-orders-block-alleged-fake-news-sites.html] that were allegedly linked to fake news about the virus. Additionally, the Health Ministry reportedly proposed amending laws that would make it punishable for healthcare workers to speak to the press or public about an outbreak.^[Barron, Laignee. February 28, 2020. Time. https://time.com/5792180/southeast-asia-undetected-coronavirus/] Amid the pandemic, accurate information is one of the most important assets and tools to overcome the crisis. 

Ultimately, Myanmar is an example of how developing countries are struggling during a crisis they are not prepared for. The pandemic is amplifying persisting economic, political, and social disparities worldwide. Countries that are devoid of testing capacities, social safety nets, economic reserves, and comprehensive policies will face unparalleled difficulties in overcoming this crisis. Similarly, the battle against the virus will be a fight of political systems to prove their capabilities. This pandemic has demonstrated the importance of transparency, honesty, open communication, and collaboration. 
