---
title: 'Codebook CoronaNet'
author: 
date: 
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


*Download* the [codebook here](data/codebook/CoronaNet_Codebook.pdf).


## Terms and Conditions for Citing CoronaNet {-}

By using this site or downloading data from CoronaNet, users agree to the following:

  *   To use and/or download the data only for private or personal, non-commercial purposes
  *   To cite the source of the data and
  *   To accept disclaimers and restrictions of rights and liability converning the data
  

|
|

## Citing CoronaNet {-}

For non-academic purposes, please cite the information in CoronaNet as:

  *   Source: CoronaNet Research Project
  
For academic purposes, please cite the information in CoronaNet and/or user’s guide using the following citation:

  *   APA: Cheng, C., Barcelo, J., Hartnett, A.S., Kubinec, R., & Messerschmidt, L. (2020). CoronaNet—Tracking              governments COVID-19 responses. https://www.coronanet-project.org
  *   Chicago: Cheng, Cindy, Joan Barcelo, Allison Spencer Hartnett, Robert Kubinec, and Luca Messerschmidt. 2020.          “CoronaNet -Tracking Governments COVID-19 Responses.” https://www.coronanet-project.org
  
The dataset in combination with the paper published in “Nature Human Behavior” can be cited the following way:

  *   Cheng, Cindy, Joan Barceló, Allison Hartnett, Robert Kubinec, and Luca Messerschmidt. 2020. COVID-19 Government       Response Event Dataset (CoronaNet v1.0). Nature Human Behaviour (2020). 
      https://doi.org/10.1038/s41562-020-0909-7

|
|

## CoronaNet Research Group {-}

The project is organized and led by:

  *   [Joan Barcelo](https://sites.google.com/view/joanbarcelo/home?authuser=1) (NYU Abu Dhabi)
  *   [Cindy Cheng](http://cindyyawencheng.com/) (Hochschule für Politik at the TU Munich)
  *   [Allison Spencer Hartnett](http://www.allisonhartnett.io/) (Yale University)
  *   [Robert Kubinec](http://www.robertkubinec.com/#about) (NYU Abu Dhabi)
  *   [Luca Messerschmidt](https://lumesserschmidt.github.io/aboutme/) (Hochschule für Politik at the TU Munich)


|
|

  
## What is the CoronaNet Research Project {-}

The CoronaNet Research Project compiles a database on government responses to the corona virus. Our main focus is to collect as much information as we can about the various fine-grained actions governments are taking to defeat the coronavirus. This includes not only gathering information about which governments are responding to the coronavirus, but who they are targeting the policies toward (e.g. other countries), how they are doing it (e.g. travel restrictions, banning exports of masks) and when they are doing it. Together with over 500 scholars and research assistants from all over the world we present an initial release of a large hand-coded dataset of more than 15,000 separate policy announcements from governments around the world visible since December 31st 2019.

The data yields detailed information on

  *   The levels of government responding to the corona virus crisis (e.g. national, regional/state, local/municipal)
  
  *   Specific actions taken (e.g. travel bans, investments in the public health sector, etc.)
  
  *   Geographical areas targeted by these measures
  
  *   Who or what they are targeting (e.g. foreigners, ventilators)
  
  *   Compliance mechanisms (e.g., mandatory or voluntary)
  
  *   Timing of policy responses
  

|
|

  
## CoronaNet Dataset Variable Definitions {-}

| variable_name        | variable_description                                                                                                                                                              | variable_categories (first_stage_division)                                                                                                                                                                                                                                                                                                                                                                                                     | sub_variables_description                                                                                           |
|----------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------|
| record_id            | Unique identifier for each policy record                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                                                                                     |
| policy_id            | Unique identifier for one policy: Updates and corrections have the same policy_id as the original record.                                                                         |                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                                                                                     |
| recorded_date        | When the record was entered into our data                                                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                                                                                     |
| date_updated         | Displays the last update date of the respective policy                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                                                                                     |
| date\_ announced     | When the policy goes into effect                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                                                                                     |
| date_start           | Date that the government policy takes effect.                                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                                                                                     |
| date_end             | Date that the government policy ends or is projected to end.                                                                                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                                                                                     |
| entry_type           | Whether the record is new, meaning no restriction had been in place before, or an update (restriction was in place but changed). Corrections are corrections to previous entries. | Update New_entry NA                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                     |
| update_type          | In case the policy is an update, shows whether policy has changed or was ended.                                                                                                   | End of Policy Change of Policy NA                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                     |
| event\_ description  | A short description of the policy change                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                                                                                     |
| domestic_policy      | Marks whether the initiator of a policy is the same as the target of the policy (1) or not (0).                                                                                   | 1 0                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                     |
| type                 | The category and sub- category of the policy                                                                                                                                      | Restriction and Regulation of Government Services                                                                                                                                                                                                                                                                                                                                                                                              | "Public libraries"                                                                                                  |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Public museums/galleries"                                                                                          |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "No special population targeted"                                                                                    |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Issuing of permits/certificates and/or processing of government documents"                                         |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Other public facilities"                                                                                           |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Regulated government working hours (e.g. work from home policies for government workers)"                          |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "All non-essential government services regulated"                                                                   |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "All essential government services regulated"                                                                       |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Other workers where the distinction between essential or non-essential is not explictely made"                     |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Parks"                                                                                                             |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Other public outdoor spaces"                                                                                       |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Regulations on government meetings (including e.g. suspension of parliament)"                                      |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Regulations on publicly provided waste management services"                                                        |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Other population not specifed above"                                                                               |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Public courts"                                                                                                     |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Campsites"                                                                                                         |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Beaches"                                                                                                           |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "People of a certain age"                                                                                           |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Unspecified public facilities"                                                                                     |
|                      |                                                                                                                                                                                   | Quarantine                                                                                                                                                                                                                                                                                                                                                                                                                                     | Self-Quarantine (i.e. quarantine at home)                                                                           |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | Quarantine outside the home or government facility (i.e. quarantine in a hotel)                                     |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | Other Quarantine                                                                                                    |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | Government Quarantine (i.e. quarantine at a government hotel or facility)                                           |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | Quarantine only applies to people of certain ages                                                                   |
|                      |                                                                                                                                                                                   | Health Resources                                                                                                                                                                                                                                                                                                                                                                                                                               | Other Health Infrastructure                                                                                         |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Masks"                                                                                                             |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Other Health Materials"                                                                                            |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Public Testing Facilities (e.g. drive-in testing for COVID-19)"                                                    |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Hospitals"                                                                                                         |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Temporary Quarantine Centers"                                                                                      |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Temporary Medical Centers"                                                                                         |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Hand Sanitizer"                                                                                                    |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Personal Protective Equipment"                                                                                     |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Test Kits"                                                                                                         |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Other Heath Staff"                                                                                                 |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Ventilators"                                                                                                       |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Unspecified Health Staff"                                                                                          |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Health Research Facilities"                                                                                        |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Doctors"                                                                                                           |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Nurses"                                                                                                            |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Health Volunteers"                                                                                                 |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Unspecified Health Infrastructure"                                                                                 |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Unspecified Health Materials"                                                                                      |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Medicine/Drugs"                                                                                                    |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Vaccines"                                                                                                          |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Health Insurance"                                                                                                  |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | NA                                                                                                                  |
|                      |                                                                                                                                                                                   | External Border Restrictions                                                                                                                                                                                                                                                                                                                                                                                                                   | "Other External Border Restriction"                                                                                 |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Travel History Form (e.g. documents where traveler has recently been)"                                             |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Visa restrictions (e.g. suspend issuance of visa)"                                                                 |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Health Screenings (e.g. temperature checks)"                                                                       |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Health Certificates"                                                                                               |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Visa extensions (e.g. visa validity extended)"                                                                     |
|                      |                                                                                                                                                                                   | Lockdown                                                                                                                                                                                                                                                                                                                                                                                                                                       | "Lockdown applies to all people"                                                                                    |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Lockdown only applies to people of certain ages"                                                                   |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Lockdown only applies to people with certain health conditions"                                                    |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Lockdown only applies to people with a condition not specified above"                                              |
|                      |                                                                                                                                                                                   | Health Testing                                                                                                                                                                                                                                                                                                                                                                                                                                 | \-                                                                                                                  |
|                      |                                                                                                                                                                                   | Social Distancing                                                                                                                                                                                                                                                                                                                                                                                                                              | "All public spaces / everywhere"                                                                                    |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Inside public or commercial building (e.g. supermarkets)"                                                          |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Other Mask Wearing Policy"                                                                                         |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Unspecified Mask Wearing Policy"                                                                                   |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Wearing masks"                                                                                                     |
|                      |                                                                                                                                                                                   | Closure and Regulation of Schools                                                                                                                                                                                                                                                                                                                                                                                                              | "Preschool or childcare facilities (generally for children ages 5 and below)"                                       |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Primary Schools (generally for children ages 10 and below)"                                                        |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Secondary Schools (generally for children ages 10 to 18)"                                                          |
|                      |                                                                                                                                                                                   | Health Monitoring                                                                                                                                                                                                                                                                                                                                                                                                                              | \-                                                                                                                  |
|                      |                                                                                                                                                                                   | Public Awareness Measures                                                                                                                                                                                                                                                                                                                                                                                                                      | Disseminating information related to COVID-19 to the public that is reliable and factually accurate                 |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | Both Disseminating and Gathering information related to COVID-19                                                    |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | Gathering information related to COVID-19 from the public                                                           |
|                      |                                                                                                                                                                                   | Restriction and Regulation of Businesses                                                                                                                                                                                                                                                                                                                                                                                                       | "Retail Businesses                                                                                                  |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Shopping Centers"                                                                                                  |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Non-Essential Commercial Businesses"                                                                               |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Personal Grooming Businesses (e.g. hair salons)"                                                                   |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Other Non-Essential Businesses"                                                                                    |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "All or unspecified non- essential businesses"                                                                      |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "All or unspecified essential businesses"                                                                           |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Other Essential Businesses"                                                                                        |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Supermarkets/grocery stores"                                                                                       |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Pharmacies"                                                                                                        |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Construction"                                                                                                      |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Telecommunications"                                                                                                |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Information service activities"                                                                                    |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Mining and quarrying"                                                                                              |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Publishing activities"                                                                                             |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Warehousing and support activities for transportation"                                                             |
|                      |                                                                                                                                                                                   | Restrictions of Mass Gatherings                                                                                                                                                                                                                                                                                                                                                                                                                | "Cancellation of an annually recurring event"                                                                       |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Cancellation of a recreational or commercial event"                                                                |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Postponement of an annually recurring event"                                                                       |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Postponement of a recreational or commercial event"                                                                |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Prison population reduced (e.g. early release of prisoners)"                                                       |
|                      |                                                                                                                                                                                   | Declaration of Emergency                                                                                                                                                                                                                                                                                                                                                                                                                       | \-                                                                                                                  |
|                      |                                                                                                                                                                                   | Internal Border Restrictions                                                                                                                                                                                                                                                                                                                                                                                                                   | \-                                                                                                                  |
|                      |                                                                                                                                                                                   | New Task Force, Bureau or Administrative Configuration                                                                                                                                                                                                                                                                                                                                                                                         | "Other Administrative Configurations"                                                                               |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Existing government entity given new powers"                                                                       |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "New Task Force or Bureau (i.e. establishment of a temporary body)"                                                 |
|                      |                                                                                                                                                                                   | Curfew                                                                                                                                                                                                                                                                                                                                                                                                                                         | \-                                                                                                                  |
|                      |                                                                                                                                                                                   | Hygiene                                                                                                                                                                                                                                                                                                                                                                                                                                        | "Other Areas Hygiene Measures Applied"                                                                              |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Hygiene measures for commercial areas"                                                                             |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Hygiene measures for public areas"                                                                                 |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Burial procedures"                                                                                                 |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Hygiene measures for public transport"                                                                             |
|                      |                                                                                                                                                                                   | Anti-Disinformation Measures                                                                                                                                                                                                                                                                                                                                                                                                                   | "No special population targeted"                                                                                    |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "People with certain health conditions"                                                                             |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | "Other population not specifed above"                                                                               |
|                      |                                                                                                                                                                                   | Other Policy Not Listed Above                                                                                                                                                                                                                                                                                                                                                                                                                  | \-                                                                                                                  |
| index_high_est       | The high (95% posterior density) estimate of the country policy activity score (0-100).                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                                                                                     |
| index_med_est        | The median (most likely) estimate of the country policy activity score (0- 100).                                                                                                  |                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                                                                                     |
| index_low_est        | The low (95% posterior density) estimate of the country policy activity score (0-100)                                                                                             |                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                                                                                     |
| index_country\_ rank | The relative rank by each day for each country on the policy activity score.                                                                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                                                                                     |
| correct_type         | Indicates whether an entry was corrected by the coder.                                                                                                                            | original correction                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                     |
| country              | The country initiating the policy                                                                                                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                                                                                     |
| init_country\_ level | Whether the policy came from the national level or a sub-national unit                                                                                                            | National Provincial Municipal Other (e.g., county)                                                                                                                                                                                                                                                                                                                                                                                             | Documents the province from which a policy is initiated, if applicable.                                             |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | City from which a policy is initiated, if applicable.                                                               |
| source_corr\_ type   | Shows, in case of an entry correction, whether a new source was added                                                                                                             | Use the old source Add a new source                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                     |
| target_geog\_ level  | Whether the target of the policy is a country as a whole or a sub-national unit of that country                                                                                   | One or more countries, but not all countries All countries A geographical or administrative unit within a country One or more countries and one or more regional groupings One or more regional groupings An international                                                                                                                                                                                                                     | Which foreign country a policy is targeted at (i.e. travel policies)                                                |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | This variable documents the region or regions that is/are the targets of a particular government policy.            |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | Targeted province of a policy, if applicable.                                                                       |
|                      |                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                | Targeted city of a policy, if applicable.                                                                           |
|                      |                                                                                                                                                                                   | organization (e.g. World Health Organization)                                                                                                                                                                                                                                                                                                                                                                                                  | This variable documents the subnational region or regions that is/are the target of a particular government policy. |
| target_who\_ what    | Who the policy is targeted at                                                                                                                                                     | All Travelers (Citizen Travelers + Foreign Travelers) All (Travelers + Residents) All Residents (Citizen Residents +Foreign Residents) Health-Related Supplies Foreign Travelers Citizen Travelers Health Staff All Foreign Nationals (Foreign Residents + Foreign Travelers) All Citizens (Citizen Residents + Citizen Travelers) Citizen Residents Foreign Residents (Foreign Nationals Residing in the Country) Health-Infrastructure Other |                                                                                                                     |
| target_direction     | Whether a travel-related policy affects people coming in (Inbound) or leaving (Outbound)                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                                                                                     |
| travel\_ mechanism   | If a travel policy, what kind of transportation it affects                                                                                                                        | All kinds of transport Flights Trains Land Border Flights Seaports Cruises Ferries Buses Not Applicable Other                                                                                                                                                                                                                                                                                                                                  |                                                                                                                     |
| compliance           | Whether the policy is voluntary or mandatory                                                                                                                                      | Mandatory With Legal Penalties Mandatory with Fines Mandatory (Unspecified/Implied) Mandatory with Exceptions Recommended/Voluntary but no penalties                                                                                                                                                                                                                                                                                           |                                                                                                                     |
| enforcer             | What unit in the country is responsible for enforcement                                                                                                                           | National government Ministry/Department of Health Military Provincial/state government Municipal government Police                                                                                                                                                                                                                                                                                                                             |                                                                                                                     |
| link                 | A link to at least one source for the policy                                                                                                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                                                                                     |
| ISO_A3               | 3-digit ISO country codes                                                                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                                                                                     |
| ISO_A2               | 2-digit ISO country codes                                                                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                                                                                     |
