---
title: "Contact"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

For English and German inquiries:

Luca Messerschmidt | Hochschule für Politik at the TU Munich | luca.messerschmidt @ hfp.tum.de | Richard-Wagner-Street 1 | 80333 Munich, Germany

Chinese:

Cindy Cheng | Hochschule für Politik at the TU Munich | cindy.cheng @ hfp.tum.de | Richard-Wagner-Street 1 | 80333 Munich, Germany

Spanish:

Joan Barceló | Social Science Division, New York University – Abu Dhabi | joan.barcelo @ nyu.edu


Arabic: 

Robert Kubinec | Social Science Division, New York University – Abu Dhabi | rmk7 @ nyu.edu


Any media and press related questions can also be asked via this [form](https://forms.gle/2Zc5Rrdq9J43b7NR9).


# Disclaimer for CoronaNet {-}

If you require any more information or have any questions about our site's disclaimer, please feel free to contact us by email at  luca.messerschmidt @ hfp.tum.de.


All the information on this website is published in good faith and for general information purpose only. CoronaNet does not make any warranties about the completeness, reliability and accuracy of this information. Any action you take upon the information you find on this website, is strictly at your own risk. will not be liable for any losses and/or damages in connection with the use of our website.

From our website, you can visit other websites by following hyperlinks to such external sites. While we strive to provide only quality links to useful and ethical websites, we have no control over the content and nature of these sites. These links to other websites do not imply a recommendation for all the content found on these sites. Site owners and content may change without notice and may occur before we have the opportunity to remove a link which may have gone ‘bad'.

Please be also aware that when you leave our website, other sites may have different privacy policies and terms which are beyond our control. Please be sure to check the Privacy Policies of these sites as well as their "Terms of Service" before engaging in any business or uploading any information.

## Consent {-}

By using our website, you hereby consent to our disclaimer and agree to its terms.

## Update {-}

Should we update, amend or make any changes to this document, those changes will be prominently posted here.
