---
title: "In the Media"
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<style>
body {
text-align: justify}
</style>

***

May 8, 2020: **Lowy Institute**, [Indonesia’s democracy is flawed, but do enough people care?](https://www.lowyinstitute.org/the-interpreter/indonesia-s-democracy-flawed-do-people-care) by our member Fadhilah Fitri Primandari 

May 5, 2020: **Washington Post**, [During the pandemic, Russia and the U.S. have these 3 things in common](https://www.washingtonpost.com/politics/2020/05/05/during-pandemic-russia-us-have-these-3-things-common/) by our member Caress Schenk

April 25, 2020: **web.de**, [So weitreichend sind Deutschlands Corona-Maßnahmen im weltweiten Vergleich](https://web.de/magazine/politik/coronavirus-deutschland-massnahmen-weltweiten-vergleich-34630916) analyses the data and interviews CoronaNet members


***
# Initial Press Release {-}
The Press releases can be found here

+ [20200410_english](data/Press_release/Press_Release_20200415_en.pdf)

+ [20200410_german](data/Press_release/Press_Release_20200415_de.pdf)

<!-- + [20200401_arabic]() -->

+ [20200401_spanish](data/Press_release/Press_Release_20200415_sp.pdf)

+ [20200401_chinese simplified](data/Press_release/Press_Release_20200415_ch.pdf)

+ [20200401_chinese traditional](data/Press_release/Press_Release_20200415_ch_traditional.pdf)

+ [20200401_russian](data/Press_release/Press_Release_20200415_ru.pdf)

***
# Press Contact {-}

Any media and press related questions can also be directed to admin@coronanet-project.org.



