---
title: "Country Report on Chad"
description: Return to [CoronaNet](https://coronanet-project.org/)
author:
  - name: Laureen Hannig 
    affiliation: Student of International Relations and Communication Science at the University of Erfurt
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
body {
text-align: justify}
</style>


The Chadian Government reacted quickly after its neighbour Cameroon had to cope with several cases of COVID-19. The first case in Chad was recognised on March 19. Already on March 18, the government closed airports for passengers and tried to control the borders, mostly to Cameroon. This closure was extended two times and is now extended until April 25.^[Tschadinfos. April 9th, 2020. Tschadinfos.com. https://tchadinfos.com/tchad/coronavirus-les-aeroports-du-tchad-resteront-fermes-jusquau-25-avril/]

Even though Chad never had more than 50 confirmed cases, the restrictions implemented are severe. Via Twitter, the president of Chad announced on March 24 that after just one reported infected Chadian, all places of education, religious places, bars and restaurants will be closed due to the pandemic.^[Deby Itno, Idriss, March 24th, 2020. Twitter] Measures like prison inmate releases, the closure of weekly markets, the proscription of public transport followed shortly after.  Another measure was the enforcement of curfews in the capital N'Djamena and the regions of Logone Occidental, Logone Oriental, Mayo Kebbi Ouest and Mayo Kebbi Est. Most of them have a border to Cameroon. As of now (April 19) Chad has declared 33 confirmed cases of the coronavirus and 0 death, which is relatively few compared to other countries.^[Worldometers.info. April 19th, 2020. https://www.worldometers.info/coronavirus/country/chad/]  Cameroon by comparison has a total of 1017 confirmed cases^[Worlometers.info. April 19th, 2020. https://www.worldometers.info/coronavirus/country/cameroon/], which may have led to the strict and early measures in Chad. Many Chadians live and study in Cameroon. After all universities in Cameroon closed, many students wanted to go back to their families in Chad. At official borders, there are health tests but many Chadian students found and still find illegal ways to enter Chad without being tested. On March 30, the Chadian Minister of Public Health presented this issue, but the situation on the border to Cameroon has not changed yet.^[Dabesne, Moïsne. March 31st, 2020. Tschadinfos.com. https://tchadinfos.com/sante/coronavirus-pourquoi-le-retour-clandestin-des-etudiants-tchadiens-bloques-au-cameroun-i]  
The president of Chad, Idriss Deby Itno, informs the public on a regular basis via Twitter and his website. In most of the statements; however, it is unclear whether the mandatory measures are enforced with penalties, and if so, of what kind. Nonetheless, the Government and Ministry of Public Health tries to inform the citizens of all the new developments and taken measures. To accomplish this, a communication unit within the Ministry of Public Health was formed.^[Charfadine, Al-mardi. April 11th, 2020. Tschadinfos.com. https://tchadinfos.com/sante/coronavirus-la-cellule-de-veille-designe-un-porte-parole/] Whether this unit is working and really has an impact on the Chadians is still unclear. It seems like the Chadian population still has problems abiding by the government’s measures. For example, there are students returning illegally to Chad and people still celebrating and meeting without taking the danger of COVID-19 seriously.^[Présidence de la République du Tschad. April 13th, 2020. https://www.presidence.td/fr-news-4198.html] 

People from rural areas are often mentioned in the official statements. They are told how to improve hygiene and asked to avoid social contact. It seems that women are acutely suffering from the government’s measures, such as those who earn money as a saleswoman in one of the weekly markets. These markets are now closed and if they try to open up are stormed by military and security forces. To give just one example, the security forces forcibly closed a weekly market in Koundoul near the capital N’Djamena, which left behind women scared to lose their income.^[Beramgoto, Alexis. April 5th, 2020. Tschadinfos.com. https://tchadinfos.com/tchad/coronavirus-fermeture-forcee-du-marche-hebdomadaire-de-koundoul/]  The Government has adopted strict enforcement, with many of the measures and their violations under the penal code.^[Présidence de la République du Tschad. April 13th, 2020. https://www.presidence.td/fr-news-4198.html] However, there are probably still loopholes if they have not managed to fully shut borders and close markets without security forces. 

Another issue that could limit the impact of several measures is the poverty especially in rural areas. Women are working for income on markets that are now closed and water and hand sanitizer are not available everywhere. The government of Idriss Deby Itno is in contact with the owners of businesses to implement policies to help them. For the next 6 months, access to water will be free of charge.^[Tschadinfos. April 16th, 2020. Tschadinfos.com. https://tchadinfos.com/tchad/coronavirus-ceux-qui-nont-pas-de-robinets-peuvent-payer-les-branchements-et-profiter-gratuitement-pendant-six-mois-khoubra-mahamat-itno/] This action may save families from poverty and increase the likelihood of Chadians washing their hands regularly. But after 6 months these problems will appear again, so limited free access to water may not be enough.

Something many countries are struggling with is the obligation to wear face covering masks. In Chad, this obligation was announced quite early on April 14.^[Présidence de la République du Tschad. April 13th, 2020. https://www.presidence.td/fr-news-4198.html] Whether this obligation is able to stop the outbreak of the virus is unclear. Many countries are enforcing a similar measure limited to busses and trains, but the Chad banned public transport weeks ago. Furthermore, it is too early to say if there are enough masks for everyone. It does not seem so, because in his statement, the president already declared that scarfs and other materials can be alternatives. 

Chad has to face two main issues in order to avoid an outbreak of the coronavirus in the next weeks. A solution on how to deal with returning students from Cameroon has to be found and if the access to hand sanitizer, masks and water is still not free and open to everyone, the low number of cases will not last. But right now, except for the few loopholes and issues, the measures seem to work. 33 cases, 8 recovered and 0 deaths on April 19 are excellent comparatively speaking.^[Worldometers.info. April 19th, 2020. https://www.worldometers.info/coronavirus/country/chad/]  


## About the author {-}
Country Report by Laureen Hannig, 20, student of International Relations and Communication Science.


  
  


