---
title: "The Impact of Government Responses to COVID-19 on Women´s Reproductive Health and Rights"
description: Return to [CoronaNet](https://coronanet-project.org/)
author:
  - name: Ines Böhret 
    url: https://www.linkedin.com/in/ines-boehret/?originalSubdomain=de
    affiliation: University of Manchester
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
body {
text-align: justify}
</style>

*“We have seen how the virus does not discriminate, but its impacts do”* ^[Guterres, A. 2020. “We Are All in This Together: Human Rights and COVID-19 Response and Recovery | United Nations.” Accessed April 28, 2020. https://www.un.org/en/un-coronavirus-communications-team/we-are-all-together-human-rights-and-covid-19-response-and]

Epidemics often have a gendered impact by increasing the vulnerability of women and girls. Yet, in many cases, public responses have failed to mitigate these effects and have even strengthened disparities by adopting discriminating policies. This paper provides an overview of the current governmental policies, implemented in response to the COVID-19 pandemic, that have a direct or indirect impact on the reproductive rights and health of women. The dataset by Coronanet^[Cheng, Cindy, Joan Barcelo, Hartnett, Allison, Robert Kubinec, and Luca Messerschmidt. 2020. “Coronanet: A Dyadic Dataset of Government Responses to the COVID-19 Pandemic: BETA Version 1.0.” Accessed April 22, 2020] was searched for policies relating to reproductive and maternal health. While there are policies aimed at supporting and protecting pregnant and in labor women, several governmental measures have the potential to increase gender inequalities. Within the response to the current pandemic, women's rights are being violated. Governments need to address the reproductive health and rights of women and should be reflected in their policies. 

Social inequalities shape the disparity of disasters. Additionally, the gendered dimension of diseases can be increased by response measures. The disproportionate effect of epidemics on women has been discussed regarding previous outbreaks and the need to prevent the violation of women´s rights through disaster responses.^[Smith, Julia. 2019. “Overcoming the ‘Tyranny of the Urgent’: Integrating Gender into Disease Outbreak Preparedness and Response.” Gender & Development 27 (2): 355–69. https://doi.org/10.1080/13552074.2019.1615288;  Davies, S., E., and B. Bennet. 2016. “A Gendered Human Rights Analysis of Ebola and Zika: Locating Gender in Global Health Emergencies.” International Affairs 92 (5): 1041–60.https://doi.org/10.1111/1468-2346.12704] However, the policies in response to COVID-19 often neglect the needs and rights of women and indirectly exacerbates structures of inequality. For example, the closure of kindergartens and schools has increased existing inequalities within gendered unpaid labor ^[United Nations, 9. April 2020, https://www.unwomen.org/-/media/headquarters/attachments/sections/library/publications/2020/policy-brief-the-impact-of-covid-19-on-women-en.pdf?la=en&vs=1406 ] Furthermore, the restrictions of services such as the closure of women´s shelters have made women more vulnerable to gender-based violence.^[OHCHR. 2020. “COVID-19 and Women´s Human Rights: Guidance: What Is the Impact of Covid-19 on Gender-Based Violence?” Accessed April 29, 2020. https://www.ohchr.org/Documents/Issues/Women/COVID-19_and_Womens_Human_Rights.pdf.] Thus, the government responses to COVID-19 have the potential to increase gender-based inequalities. 

There have been a few policies that acknowledge the reproductive and maternal rights of women concerning the biomedical needs of the pandemic. Other policies severely violate women´s access to health. Some governments have aimed to mitigate gender-based inequalities regarding reproductive and maternal health caused by the pandemic. For example, in England and Wales, home abortions have been legalized. Additionally, in the Czech Republic and Finland, bans on visitors in hospitals do not apply to pregnant women.^[Cheng, Cindy, Joan Barcelo, Hartnett, Allison, Robert Kubinec, and Luca Messerschmidt. 2020. “Coronanet: A Dyadic Dataset of Government Responses to the COVID-19 Pandemic: BETA Version 1.0.” Accessed April 22, 2020.] Despite these progressive measures, many policies seem to interfere with the reproductive rights and maternal health of women. The next section focuses on the policies targeting reproductive rights, antenatal care, and birthing rights. 

Previous epidemics have revealed how reproductive rights can be politized in times of emergency.^[Davies, S., E., and B. Bennet. 2016. “A Gendered Human Rights Analysis of Ebola and Zika: Locating Gender in Global Health Emergencies.” International Affairs 92 (5): 1041–60.https://doi.org/10.1111/1468-2346.12704.] In response to COVID-19, there have been measures that reduce access to reproductive health services. For example, in some US states, abortions have been restricted or banned as “non-essential medical procedures”.^[Abrams, A. 2020. “COVID-19 Could Permanently Make Abortions Harder to Access Nationwide.” Time, April 7. Accessed April 29, 2020. https://www.unfpa.org/sites/default/files/resource-pdf/COVID-19_Update_No-2_UNFPA_Supplies_v5.pdf] Shutdowns of manufacturers and lockdowns in many states have also led to the restricted access of contraception.^[United Nations. 2020. “Policy Brief: The Impact of COVID-19 on Women.” Accessed April 29, 2020. https://www.ohchr.org/Documents/Issues/Women/COVID-19_and_Womens_Human_Rights.pdf.  and UNFPA, 30. March 2020, https://www.unfpa.org/resources/unfpa-supplies-covid-19-update-30-march-2020 ] Such policies are predicted to contribute to approximately 7 million unintended pregnancies,^[UN News. 2020. “COVID-19 Could Lead to Millions of Unintended Pregnancies, New UN-Backed Data Reveals.” Accessed April 29, 2020. https://journals.plos.org/plosone/article/file?type=printable&id=10.1371/journal.pone.0165621.] impacting the socioeconomic status of women and increasing their risk factors for maternal mortality.^[Hall, Jennifer Anne, Geraldine Barrett, Tambosi Phiri, Andrew Copas, Address Malata, and Judith Stephenson. 2016. “Prevalence and Determinants of Unintended Pregnancy in Mchinji District, Malawi; Using a Conceptual Hierarchy to Inform Analysis.” PloS one 11 (10): e0165621.https://doi.org/10.1371/journal.pone.0165621] 

COVID-19 response policies negatively impact maternity care. The organization Human Rights in Childbirth has documented restrictions of maternal rights during the pandemic. These include the de-prioritization and closure of maternity services, denial of birth companion, and obstetric violence.^[Drandić, D. 2020. “HRiC Informs European Parliament Action on Maternity Care During COVID-19.” Accessed April 24, 2020. http://humanrightsinchildbirth.org/index.php/2020/04/23/hric-informs-european-parliament-action-on-maternity-care-during-covid-19/.] The dataset reveals that on the national level, at least four policies on four different continents have turned maternity units or women´s hospitals into COVID-19 treatment centers.^[Cheng, Cindy, Joan Barcelo, Hartnett, Allison, Robert Kubinec, and Luca Messerschmidt. 2020. “Coronanet: A Dyadic Dataset of Government Responses to the COVID-19 Pandemic: BETA Version 1.0.” Accessed April 22, 2020.] In Angola, Brazil, Myanmar, and Russia, health care institutions originally designed to support women´s health have been used for patients infected with COVID-19. It remains unclear to what extent these reductions in maternal health services have been reallocated. These measures put additional pressure on staff and their resources, increasing the risk for restricted care and obstetric violence.^[Rocca-Ihenacho, Lucia, and Cristina Alonso. 2020. “Where Do Women Birth During a Pandemic? Changing Perspectives on Safe Motherhood During the COVID-19 Pandemic.” J Glob Health Sci 2.https://doi.org/10.35500/jghs.2020.2.e4]  

Restrictive policies have directly targeted pregnant women, while birthing rights have been denied despite the guidance of the WHO.^[WHO. 2020. “Pregnancy, Childbirth, Breastfeeding and COVID-19.” Accessed April 23, 2020. https://www.who.int/reproductivehealth/publications/emergencies/COVID-19-pregnancy-ipc-breastfeeding-infographics/en/.] Access to consultations and antenatal care has been restricted or outlawed and women in labor have been denied birth companions. Bulgaria has suspended consultations for pregnant women and Guatemala has restricted pregnant women from leaving their homes.^[Cheng, Cindy, Joan Barcelo, Hartnett, Allison, Robert Kubinec, and Luca Messerschmidt. 2020. “Coronanet: A Dyadic Dataset of Government Responses to the COVID-19 Pandemic: BETA Version 1.0.” Accessed April 22, 2020.] Additionally, various countries have applied visitor bans to hospitals and clinics lacking an exception for birth companions such as partners or doulas.^[Ibdm.] These restrictions have detrimental effects on the antenatal, perinatal, and postpartum health of women by limiting support and care while increasing levels of stress and anxiety through isolation and uncertainty.^[Oja, L. 2020. “Sexual and Reproductive Rights in Time of the Covid-19 Pandemic: Reflections and Notes.” Accessed April 23, 2020. https://www.liirioja.com/srhr-writings] 

In conclusion, there are numerous governmental responses to COVID-19 that strengthen gender inequalities and compromise women´s rights to reproductive and maternal health. The de-prioritization of women's health services directly violates women´s reproductive rights and may result in detrimental long-term effects. Zampas^[Zampas, C. 2020. “Covid 19: A Wake-up Call to Eliminate Barriers to SRHR.” Sexual and Reproductive Health Matters.http://www.srhm.org/news/covid-19-a-wake-up-call-to-eliminate-barriers-to-srhr/. Accessed April 23, 2020.] highlights that while barriers to sexual and reproductive health services have always existed for marginalized women, this may be the first time that all women, regardless of economic and ethnic backgrounds, experience negative impacts of an epidemic based on their gender. While devastating, this could be a chance to shift towards a more gender-sensitive disaster response by accounting for reproductive and maternal rights.
