---
title: "COUNTRY REPORT THE GAMBIA"
description: Return to [CoronaNet](https://coronanet-project.org/)
author:
  - name: Nadja Grossenbacher 
    url: 
    affiliation: Graduate Student at Utrecht University
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
body {
text-align: justify}
</style>

The so-called index-case in the Gambia was a 28-year-old national who arrived from London on the 15th of March. The second confirmed case was a 70-year-old Bangladeshi who had been travelling to several countries before entering the Gambia on the 14th of March.^[Covid-19 Situation report 21st & 22nd March 2020. http://www.moh.gov.gm/covid-19-report/] Unfortunately, the aforementioned person died on the 20th March 2020 and is the only confirmed Covid-19-related death in the entire country up until this point.^[Covid-19 Situation report 25th April 2020. http://www.moh.gov.gm/wp-content/uploads/2020/04/The_Gambia_COVID-19_Sitrep-24-04-2020.pdf]  The total number of confirmed cases in the Gambia as of the 25th of April is ten, eight out of whom have successfully recovered and been discharged, though one has died and one is still active.^[Covid-19 Situation report 25th April 2020. http://www.moh.gov.gm/wp-content/uploads/2020/04/The_Gambia_COVID-19_Sitrep-24-04-2020.pdf]  Despite the number of cases being quite low in an international context up until now, one might want to consider that the Gambia’s health resources unfortunately seem to be quite limited. In the entire country, which is the smallest on continental Africa ^[The Washington Post. https://www.washingtonpost.com/world/africa/borders-are-closing-to-fight-the-coronavirus-now-this-village-is-split-in-two/2020/04/01/d601cd4e-72c1-11ea-ae50-7148009252e3_story.html] and has approximately a little over 2 million inhabitants, the total number of hospitals is four^[https://fajararotarygambia.org/hospitals-clinics-health-organisations-in-gambia/], and there is only one COVID-19 testing centre, namely the Medical Research Council Unit the Gambia at the London School of Hygiene & Tropical Medicine.^[Medical Research Council Unit the Gambia.  https://www.mrc.gm/coronavirus-covid-19-information/] 

In order to prevent the spread of Covid-19, all overseaS travels for public officials of the Gambia have been suspended as of 13th March 2020.^[https://twitter.com/Presidency_GMB/status/1238492495744512002/photo/1] Once it became clear that the Coronavirus has actually made its way to the Gambia, more severe measures have been announced on the 17th of March and took effect on the 19th of March, including the suspension of public gatherings as well as the closure of schools and universities.^[Panapress. https://www.panapress.com/Coronavirus-President-Barrow-sus-a_630632827-lang2.html]  Furthermore, travellers from hotspot-countries had to undergo a 14-day-quarantine when entering the Gambia after the 17th of March.^[Twitter. https://twitter.com/Presidency_GMB/status/1240036641458225152] Two days later, flights from 13 countries to the Gambia were suspended and the mandatory 14-day-quarantine was set in place for travellers (Gambian as well as non-Gambian) from 47 different countries.^[All Africa. https://allafrica.com/stories/202003201113.html & Panapress. https://www.panapress.com/Coronavirus-Gambia-suspends-flig-a_630633225-lang2.html]  On the 20th of March, non-Gambians from hotspot countries were denied entry into the country ^[Twitter. https://twitter.com/Presidency_GMB/status/1241127410734596096 ] and on the 21st of March, the Gambia officially closed its airspace and land borders.^[Anadolu Agency. https://www.aa.com.tr/en/africa/covid-19-gambia-senegal-to-close-border-for-21-days/1776298] The closure of the land border with the Gambia’s only neighbouring country of Senegal had drastic effects for the every-day-life of some people living along the border, an example being a village literally having been split in two.^[The Washington Post. https://www.washingtonpost.com/world/africa/borders-are-closing-to-fight-the-coronavirus-now-this-village-is-split-in-two/2020/04/01/d601cd4e-72c1-11ea-ae50-7148009252e3_story.html] The latter resulted in the villagers living on the Gambian side not having access to drinking water anymore as they had used to send horse carts a quarter-mile over the border to fill jugs; these and similar daily tasks are now no longer possible due to police officers with AK-47s enforcing the official governmental measure.^[The Washington Post. https://www.washingtonpost.com/world/africa/borders-are-closing-to-fight-the-coronavirus-now-this-village-is-split-in-two/2020/04/01/d601cd4e-72c1-11ea-ae50-7148009252e3_story.html] 

As an aftermath of the official proclamation of the government, which restricts public transport to only carrying half the number of passengers per ride due to COVID-19,^[Twitter. https://twitter.com/Presidency_GMB/status/1243663823892070402/photo/1] commercial drivers have increased fares of transport.^[The Point. http://thepoint.gm/africa/gambia/article/drivers-increase-fares-amid-state-of-emergency-declaration] The latter seems like it will result in a financial loss for both the drivers and the passengers,^[The Point. http://thepoint.gm/africa/gambia/article/drivers-increase-fares-amid-state-of-emergency-declaration] which therefore adds another economic disadvantage to the already difficult situation during this crisis. As the majority of the population does not have a regular income and therefore neither has neither savings nor a social security buffer, many cannot afford basic necessities.^[President Barrow’s statement during the ECOWAS COVID19 virtual conference. Link to video:  https://www.facebook.com/watch/?v=1311450305719764] Street vendors especially appear to be highly affected, as the forced closure of shops has resulted in over a dozen people per closed shop suffering from hunger.^[Foroyaa. https://foroyaa.net/hunger-and-hardship-creep-in-as-coronavirus-enters-the-gambia/] 

On March 27th 2020, the Gambian president Adama Barrow officially declared a state of emergency for COVID-19.^[APA News. http://apanews.net/en/pays/gambie/news/gambia-declares-state-of-emergency-over-covid-19] The Gambian police has been patrolling cities and towns in the Greater Banjul Area in order to ensure the enforcement of the closure of non-essential commodity shops, bars, cafés, casinos and sporting venues.^[Journal du Cameroun. https://www.journalducameroun.com/en/gambian-police-on-raid-to-enforce-state-of-emergency/] When the state of emergency was extended for 45 days on April 3rd 2020,^[Worldaware. https://www.worldaware.com/covid-19-alert-gambia-extends-nationwide-state-emergency-45-days] anger and uneasiness was expressed over it by the population.^[Africa Feeds. https://africafeeds.com/2020/04/05/covid-19-gambians-angry-with-45-days-of-state-of-emergency/ ] Even though the president seems to be aware of the lack of access to drinking water as well as many not being able to meet their basic necessities ^[President Barrow’s statement during the ECOWAS COVID19 virtual conference. Link to video:  https://www.facebook.com/watch/?v=1311450305719764] and some voices have already suggested considering to offer a food relief for those who are economically disadvantaged,^[Africa Feeds. https://africafeeds.com/2020/04/05/covid-19-gambians-angry-with-45-days-of-state-of-emergency/ ] nothing more than a signed partnership with UNDP to close poverty and inequality gaps in rural areas^[Twitter. https://twitter.com/Presidency_GMB/status/1247901703598309377 ] on April 8th appears to have put in place in order to improve the situation. 

Although the consequences of the governmental policies convey the impression of depriving many locals of having a means of livelihood,^[Africa Feeds. https://africafeeds.com/2020/04/05/covid-19-gambians-angry-with-45-days-of-state-of-emergency/ ] Barrow emphasized that the immediate policy response is focused on saving lives, limiting the spread of the virus and managing the crisis.^[President Barrow’s statement during the ECOWAS COVID19 virtual conference. Link to video:  https://www.facebook.com/watch/?v=1311450305719764] However, one might consider questioning whether the coronavirus is the only and most problematic threat in the Gambian context given the fact that several people on the grounds have expressed their worries regarding not knowing how to feed their families. Even though limiting the spread of the virus definitely is an important mission, it might also be worth intensifying the efforts and especially their prompt implementation in order to lower the rate of people suffering from hunger as an aftermath of the policies that have been implemented to fight Covid-19 in the Gambia. 

  
  


