---
title: "USA: Comparison of 50 States' Stay At Home Orders"
description: Return to [CoronaNet](https://coronanet-project.org/)
author: 
  - name: Laura Williamson 
    url: https://www.linkedin.com/in/laura-w-605806149/
    affiliation: Colorado Christian University
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
body {
text-align: justify}
</style>

In response to the coronavirus pandemic sweeping through the United States, stay at home orders were implemented in 42 of the 50 subnational states. A stay at home order is an order issued by the executive branch of each state that encourages citizens to “stay at home unless they are engaged in certain necessary activities.”^[Colorado Official State Web Portal. May 11, 2020. Colorado Department of Public Health & Environment. https://covid19.colorado.gov/stay-home-except-essential-needs.] Although most stay at home orders bear similar characteristics, the enforcement mechanisms vary from state to state. In early April, virologist Joseph Fair said that the only way for stay at home orders to be truly effective was to universally implement them across all 50 states.^[Alex Woodward. Independent UK. April 2, 2020. Independent. https://www.independent.co.uk/news/world/americas/coronavirus-us-states-lockdown-spring-break-a9442746.html.] Despite these dire warnings, Arkansas, Iowa, Nebraska, North Dakota, South Dakota, Utah, and Wyoming refused to implement a stay at home order.^[Chris Cillizza. CNN. April 13, 2020. Cable News Network. https://www.cnn.com/2020/04/13/politics/asa-hutchison-arkansas-coronavirus/index.html.]

Whether stay at home orders will become the new norm for dealing with pandemics has yet to be seen. However, it is unsurprising that there is resistance to their implementation. The very concept of a stay at home order seems foreign to many Americans, a country that openly calls itself the “land of the free.” Psychologically, it is difficult to cope with sudden isolation. Anecdotally speaking, emotional distress is skyrocketing as a result of people being forced into sudden isolation. One emotional support hotline, the Disaster Distress Helpline, saw a 338% spike in calls during March, as economic and social distress mounted across the United States.^[Jackson, Amanda. April 10, 2020. CNN. https://www.cnn.com/2020/04/10/us/disaster-hotline-call-increase-wellness-trnd/index.html.] Lack of social contact combined with unprecedented job loss, due to business closures, created a perfect storm for individuals experiencing a deterioration in their mental health. 

Economically, the tradeoff between issuing stay at home orders and enacting preventative measures that allow greater freedom of movement is illustrated by the tradeoff between the cost of direct economic loss and the indirect cost of loss of life.^[Saphir, Ann and Jeff Mason. March 30, 2020. Reuters. https://www.reuters.com/article/us-health-coronavirus-usa-reopen-analysi/the-u-s-weighs-the-grim-math-of-death-vs-the-economy-idUSKBN21H1B4.] Evidence suggests that the economy will bounce back stronger if minimizing deaths is prioritized through stay at home orders. The states that were hesitant to implement stay at home orders were fearful of state-wide economic losses that would create ripple effects throughout the country and the world. Currently, the ultimate cost of stay at home orders is mounting in states like California, which is projected to lose $688 billion in GDP.^[Nation, Joe. CalMatters. March 30, 2020. TheNewProject. https://calmatters.org/commentary/what-a-cost-analysis-shows-of-going-back-to-work-during-the-coronavirus-pandemic-vs-californias-stay-at-home-policy/.] The top 15 states in terms of job losses, as a result of state shutdowns, all had stay at home orders in place.^[Thomas Franck. CNBC. April 2, 2020. CNBC, LLC. https://www.cnbc.com/2020/04/02/this-map-shows-states-are-seeing-the-most-job-losses-due-to-the-virus.html.]

Hot spots for the virus do not appear to be confined to one region of the country. However, the virus seems to be concentrated in coastal regions and other areas of high commerce, particularly on the East Coast.^[COVID-19 Dashboard by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University (JHU). May 11th, 2020. Johns Hopkins University of Medicine. https://coronavirus.jhu.edu/map.html.] Communities of all economic classes are being affected. Some of the hardest-hit areas have been major metropolitan cities where wealth is concentrated.^[Florida, Richard. CityLab. April 3, 2020. Bloomberg. https://www.citylab.com/equity/2019/04/economic-inequality-geographic-divide-map-census-income-data/586222/.] This can likely be attributed to the increase in social interaction that naturally occurs in highly populated areas. Still, the wealthiest Americans are the ones who will be able to afford an extended absence from work. Low-income families who depend on their weekly paycheck to survive cannot afford a stay at home order without a steady income.^[Vesoulis, Abby. TIME. March 11, 2020. TIME USA, LLC. https://time.com/5800930/how-coronavirus-will-hurt-the-poor/.] 

According to a 2018 report, states without stay at home orders ranked above the median income per capita.^[Grant Suneson. USA Today. October 8, 2018. Gannett Satellite Information Network, LLC. https://www.usatoday.com/story/money/economy/2018/10/08/wealth-america-household-income-richest-poorest-states/38051359/.] All the states that did not issue stay at home orders have relatively low rates of population density (people per square mile). As of April 7th, the states without stay at home orders were still faring better, based on infections per capita.^[Thomas C. Frohlich. USA Today. April 17. 2020. Gannett Satellite Information Network, LLC. https://www.usatoday.com/story/money/2020/04/17/states-with-the-highest-number-of-covid-19-cases/111552340/.] On average, most states issued stay at home orders a week after their first coronavirus-related death. Even when accounting for population density, states that implemented stay at home orders prior to their first reported death are outperforming those that waited to implement the orders. This implies that stay at home orders are at least moderately successful in preventing high rates of infection.

Whether stay at home orders are truly effective will not be confirmed until this crisis ends. On April 21st, prior observations were made based on reported deaths to the National Center for Disease Control (CDC). However, there is a significant lag between state-reported death rates and recorded deaths on the CDC website. With evidence emerging that a majority of new coronavirus cases in New York occurred in people who were already sheltering in place, research is needed to evaluate the effectiveness of stay at home orders and regional approaches to the virus.^[Sarah Lynch Baldwin. CBS News. May 7, 2020. CBS Interactive, Inc. https://www.cbsnews.com/news/cuomo-coronavirus-patients-new-york-at-home-not-working/.]

