
---
title: Internship
author: Research Assistant of the CoronaNet Reserach Group
date: "`r lubridate::today()`"
output: pdf_document  
---
<style>
body {
text-align: justify}
</style>
&nbsp;

To whom it may concern, 

&nbsp;
Kai Su has been interning with us since May 20th and is planning to conduct a three months internship.
 
As a volunteer and unpaid Research Assistant Intern, Kai Su will be assisting us in several areas : (1) researching what government policies his assigned country has implemented starting from the beginning of the epidemic, (2) keeping up to date with new government policy actions on a daily basis and (3) Writing country reports or creating visualizations. 
 
Kai Su will be working 20 hours a week and this work can be done remotely. We are looking forward to a productive summer with him.
 
Please do not hesitate to contact me: luca.messerschmidt@hfp.tum.de (004915736905422)
 
Sincerely,
&nbsp;



Luca Messerschmidt, Principal Investigator

&nbsp;

&nbsp;

*About CoronaNet*
The CoronaNet Research Project compiles a database on government responses to the corona virus. Our main focus is to collect as much information as we can about the various fine-grained actions governments are taking to defeat the coronavirus. This includes not only gathering information about which governments are responding to the coronavirus, but who they are targeting the policies toward (e.g. other countries), how they are doing it (e.g. travel restrictions, banning exports of masks) and when they are doing it.
&nbsp;
&nbsp;
&nbsp;

*CoronaNet Research Team*

*Joan Barceló (NYU Abu Dhabi)*

*Cindy Cheng (TU Munich)*

*Allison Spencer Hartnett (Yale University)*

*Robert Kubinec (NYU Abu Dhabi)*

*Luca Messerschmidt (TU Munich)*

