---
title: "CoronaNet Research Assistant Dashboard"
output: 
  flexdashboard::flex_dashboard
    
 # vertical_layout: fill
---

<html>
    <head>
        <meta charset="utf-8">
        <title>MiniPreview Demo</title>

        <style>
        
          /* Set border color of tab to white */
          .nav-tabs-custom > .nav-tabs > li.active {
          border-top-color: white}
                    }
        
         /* Set tab bar to grey */
        .tabset { 
             background-color: grey;
          }
        
          /* Set font color of inactive tab to grey */
              .nav-tabs-custom .nav-tabs > li > a {
                color: grey;
                font-weight: bold;
              } 
              
              /* Set font color of active tab to blue */
              .nav-tabs-custom .nav-tabs > li.active > a {
                color: white;
              } 
              
              .nav-tabs-custom .nav-tabs > li.focus > a {
                color: white;
              } 

              
              /* https://stackoverflow.com/questions/31638845/change-to-a-different-colour-for-each-bootstrap-active-tab-css*/
            .nav-tabs-custom > .nav-tabs > li > a {
                  background: ;
                  border-radius: 8px;
                  margin-right: 8px;
                  box-shadow:0 0 15px #eceefd;
            }
            
            .nav-tabs > li > a {
              background-color: #BE9FF8;
              color: #ffffff;
            }
            .nav-tabs > li.active:nth-child(1) > a {
              background-color: #FFC700;
            }
            .nav-tabs > li.active:nth-child(2) > a {
              background-color: #BE9FF8;
            }
            .nav-tabs > li.active:nth-child(3) > a {
              background-color: #F79488;
            }
            .nav-tabs > li.active:nth-child(4) > a {
              background-color: #3383FF;
            }
            
            .nav-tabs > li.focus:nth-child(1) > a {
              background-color: #FFC700;
            }
            .nav-tabs > li.focus:nth-child(2) > a {
              background-color: #BE9FF8;
            }
            .nav-tabs > li.focus:nth-child(3) > a {
              background-color: #F79488;
            }
            .nav-tabs > li.focus:nth-child(4) > a {
              background-color: #3383FF;
            }
           
          .chart-wrapper,
          .nav-tabs-custom,
          .sbframe-commentary
          {
            background: ;
            border: 1px solid #e2e2e2;
            border-radius: 15px;
            margin-bottom: 8px;
            margin-right: 8px;
            box-shadow:0 0 15px #eceefd;
          }
          a {
            color: white;
            }
          body{
            font-size: 18px;
            }
   
          .break {
                text-align: center;
            }
            .chart-title {  /* chart_title  */
              font-size: 35px;
              font-weight: bold;
              color: white;
            }
            #tools{
                background-color: #8D41D6;
              }

              
            #organization{
                background-color: #e9533d;
              }
            #communication{
                background-color: #3383FF;
              }
            
            #coding-resources{
                background-color: #FFC700;
              }
            
        
            #tools-resources{
                background-color: #BE9FF8;
              }
            
            #organization-resources{
                background-color: #F79488;
              }
            
            #ra-repository{
                background-color: #BAF300;
              }
              
          .prev-ra{
            background-color: #8D41D6;
          }
         
          .gen-country{
                background-color: #FFC700;
              }
            
          .prim-source{
                background-color: #BAF300;
              }

          details summary::-webkit-details-marker { 
           display:none;
        } 
        summary{
          color: white;
        }
        
        
        
        
        </style>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>

        <!-- MiniPreview stuff here -->
        <link href="./jquery.minipreview.css" rel="stylesheet">
        <script src="./jquery.minipreview.js"></script>
        <script>
            $(function() {
                $('#p1 a').miniPreview({ prefetch: 'pageload' });
                $('#p2 a').miniPreview({ prefetch: 'parenthover' });
                $('#p1 a').miniPreview({ prefetch: 'none' });
            });
        </script>
    </head>

<body>




Main Dashboard 
===================================== 

Welcome! Pssst... take a look around!

Row 
-------------------------------------
### Tools

* Qualtrics Survey

* <p id = "p1">
<a href="https://kubinec.shinyapps.io/corona_validate/">Shiny App</a>
</p>

* <p id = "p1">
<a href="https://docs.google.com/spreadsheets/d/1OuFhdRryq2in6DfvP2PuKoe5zTWf-kgMo3Z-cBkJWcU/edit?usp=sharing">Delete a policy entry</a>
</p>



### Organization
 
Completeness and Up-to-Dateness Sheet

* <p id = "p1">
<a href="https://docs.google.com/spreadsheets/d/1J45Gme8WoxV2CaqrhiQa2wDXazQrw99wrAzF_Ew511U/edit#gid=508634612">Countries (with subnational regions) </a>
</p>

* <p id = "p1">
<a href="https://docs.google.com/spreadsheets/d/1gNvxWSrAdrM2aj7JyQKlAdQNdBkl7kDMOdJWSZBjvj0/edit?pli=1#gid=0"> Regions </a>
</p>

#### Templates


* <p id = "p1">
<a href="https://docs.google.com/document/d/1UCy4Cr59cUlj0Uog6R9NB2DOF8i8ky8sUE48Fq6F_Yw/edit#"> Country Overview Template </a>
</p>

* <p id = "p1">
<a href="https://docs.google.com/spreadsheets/d/1wV_4QOjK0QFddz6j7jMczyXA9I3uzSU1kWAlIX6Zslg/edit#gid=14819459"> Timeline Template </a>
</p>

Row {.tabset}
-------------------------------------


### Coding Resources


#### How to ...
* <details>
  <summary>Assess the policies in your country</summary>
  <small>
   + Check out the guidelines in the [Country Overview Template](https://docs.google.com/document/d/1UCy4Cr59cUlj0Uog6R9NB2DOF8i8ky8sUE48Fq6F_Yw/edit#)
   + Check out the resources left by the previous RAs in your relevant regional/country dashboard
  </small>
</details>

* <details>
  <summary>Make a plan for coding</summary>
  <small>
   + Use the [Timeline Template](https://docs.google.com/spreadsheets/d/1wV_4QOjK0QFddz6j7jMczyXA9I3uzSU1kWAlIX6Zslg/edit#gid=14819459)
  </small>
</details>

* <details>
  <summary>Get started with coding</summary> <small>
  + <p id = "p1"> <a href= "https://nyu.zoom.us/rec/play/9NyJ1dYJ88tK3fLwYVH3FNXLkbWdbI9P2guAkYFYWGalDMHYYhVnNcFiCg7ZnuKAyGoOqGYPc_OJp6DM.St4xWFlsIjQL7arN?continueMode=true">General Training Video</a>
</p>
  +  <p id = "p1">
<a href="https://tum-conf.zoom.us/rec/play/vJF5fuGop243GdyQsQSDC_QqW426KaOshHMfqaBZnhrnViIBO1PzZ-QaZbPBtptgnr6hozgzRfrwne6q?startTime=1588513802000">Video on how to do updates <small>(Password: 7C&*60@= )</small></a>
  + [Slides on how to do corrections and updates](https://syncandshare.lrz.de/getlink/fiBsrzSRB85njWLT94zwry5H/Training_draft_16.09.pptx)
 </small>
</details>
* <details>
  <summary>Clean policies in your country</summary> 
  + Fill out the [Checklist](https://docs.google.com/spreadsheets/d/1zYqfl522nz0PiwKT2LU63IEbo-QKPwgu_bwm5qav8FU/edit?usp=sharing)
</p> 
</details>

* <details>
  <summary>Get help with coding! </summary>
  <small>
   Don't hesitate to ask questions! If you have them you can...
   1. Refer to the [Codebook](https://docs.google.com/document/d/1zvNMpwj0onFvUZ_gLl4RRjqS-clbHv3TIX6EOHofsME/edit?usp=sharing) for variable definitions
   2. Check out the FAQ in the [Shiny App](https://kubinec.shinyapps.io/corona_validate/)! It is updated weekly with the most common questions posed on #ra-chat
   3. Don't see your question there? Post it in the [#ra-chat](https://corona-govt-response.slack.com/archives/C010V8MKHK2) channel.
   4.  Reach out to your regional mangager, hogwarts channel or fellow RAs for advice
  </small>
</details>
<br/>




#### General Resources
 
* <p id = "p1">
<a href="https://docs.google.com/document/d/1zvNMpwj0onFvUZ_gLl4RRjqS-clbHv3TIX6EOHofsME/edit?usp=sharing">CoronaNet Manual</a>
</p> 



### Tools Resources

#### Qualtrics Survey
* <details>
  <summary>How to access the Qualtrics Survey</summary>
  <small>

   * You will receive access to the Qualtrics survey after having passed the training test and filling out the committment form
   * Every RA receives a personalized link to the Qualtrics survey
   * Please contact admin@coronanet-project.org if you have not recieved access to the survey (note, there may be a lag of a few days before you receive access)
  </small>
</details>



#### Shiny App
* <details>
  <summary>How to Access the Shiny App</summary>
  <small>
  
    * You need an email invitation to access the Shiny App
    * Check your spam folders for such an invitation
    * If you have never received an invitation, post in the #record-tracker app and someone will add you
      </small>
</details>

* How to use the Shiny App

  + <p id = "p1">
<a href= "https://syncandshare.lrz.de/getlink/fiPF5Zf8GPfBvSYeWsoZeyww/how_to_use_shiny_app.mp4">Specific uses</a>
</p> 

  + <p id = "p1">
<a href= "https://docs.google.com/document/d/1MgZ5KSll-KGRlIJEot6j-SOgLac8C5og_3K5S_nAYZA/edit?usp=sharing">
Text and Screenshots</a>
</p> 

<br/>


#### Delete a Policy

* <details>
  <summary>When to delete a policy</summary>
  <small>
   * There are duplicate policies
   * It is easier to delete a policy and start over than to correct it
   * The policy does not belong in the dataset
</small>
</details>


### Organization Resources

* How to fill out Completeness and  Up-to-Dateness Forms
  + <p id = "p1">
<a href= "https://www.dropbox.com/s/et6swhdzqy9u66m/Up-To-Dateness%20and%20Completeness%20Tutorial.mp4?dl=0"> Video (note, need to make a new one) </a>
</p> 


#### Templates

* How to use the Timeline Template  

### Communication

* Weekly Meetings
* <p id = "p1"><a href= "https://tum-conf.zoom.us/j/92401524948"> Community Hangout Room <small> (Password: 12345) </small> </a>
</p> 
* <p id = "p1"><a href= "https://twitter.com/CoronaNet_org"> CoronaNet Twitter Feed </a>
</p>
*  <p id = "p1"><a href= "https://www.linkedin.com/groups/8982369/"> Connect to CoronaNet on LinkedIn </a>
</p>
*  <p id = "p1"><a href= "https://www.coronanet-project.org/ra_call.html"> Invite others to join CoronaNet! </a>
</p>
* <details>
  <summary>Saying goodbye? Before you go...</summary>
  <small>
  
    * Please make sure to contact your regional manager to let them know that you'll be leaving
    * If you have any useful information about your country that you would like to pass on, please remember to upload them to your relevant country/sub-national region folder so that the new RA can access them under 'Previous RA Material'
    * Please fill out this <p id = "p1"> <a href= "https://docs.google.com/forms/d/e/1FAIpQLSc-yn3BuPxSBx-wskp_0gocPYWP2BVtvf1BMtrdP_I7HblRSw/viewform"> exit survey </a> </p> to let us know about your experience with us and how we can do better! 
      </small>
</details>



Northern Africa {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar} 
-------------------------------------
**Northern Africa**
**Regional Manager**

Naela Elmore

Row
-------------------------------------


### General Country Information {.gen-country}
* Algeria
* Egypt
* Libya
* Morocco
* Sudan
* Tunisia

Row
-------------------------------------
### Previous RA Material { .prev-ra }

* Algeria
* Egypt
* Libya
* Morocco
* Sudan
* Tunisia

### Primary Sources for Old Policies {.prim-source}

* Algeria
* Egypt
* Libya
* Morocco
* Sudan
* Tunisia



Eastern Africa {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar} /// inputs in sidebar
-------------------------------------
**Eastern Africa**
**Regional Manager**

Sanjana Jain

Row
-------------------------------------


### General Country Information {.gen-country}
* Burundi
* Comoros
* Djibouti
* Eritrea
* Ethiopia
* Kenya
* Madagascar
* Mauritius
* Rwanda
* Seychelles
* Somalia
* South Sudan
* Uganda
* Tanzania

Row
-------------------------------------
### Previous RA Material { .prev-ra }

* Burundi
* Comoros
* Djibouti
* Eritrea
* Ethiopia
* Kenya
* Madagascar
* Mauritius
* Rwanda
* Seychelles
* Somalia
* South Sudan
* Uganda
* Tanzania

### Primary Sources for Old Policies {.prim-source}

* Burundi
* Comoros
* Djibouti
* Eritrea
* Ethiopia
* Kenya
* Madagascar
* Mauritius
* Rwanda
* Seychelles
* Somalia
* South Sudan
* Uganda
* Tanzania



Central Africa {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar} /// inputs in sidebar
-------------------------------------
**Central Africa**
**Regional Manager**

Ryan Kim
Elif Çalışkan

Row
-------------------------------------


### General Country Information {.gen-country}
* Cameroon
* Central African Republic
* Chad
* Republic of the Congo
* Democratic Republic of the Congo
* Equatorial Guinea
* Gabon
* Sao Tome and Principe

Row
-------------------------------------
### Previous RA Material { .prev-ra }

* Cameroon
* Central African Republic
* Chad
* Republic of the Congo
* Democratic Republic of the Congo
* Equatorial Guinea
* Gabon
* Sao Tome and Principe

### Primary Sources for Old Policies {.prim-source}

* Cameroon
* Central African Republic
* Chad
* Republic of the Congo
* Democratic Republic of the Congo
* Equatorial Guinea
* Gabon
* Sao Tome and Principe



Southern Africa {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar} /// inputs in sidebar
-------------------------------------
**Southern Africa**
**Regional Manager**

Klea Vogli & Mia Balice

Row
-------------------------------------


### General Country Information {.gen-country}
* Angola
* Botswana
* Eswatini
* Lesotho
* Namibia
* South Africa
* Zambia
* Zimbabwe
* Malawi
* Mozambique

Row
-------------------------------------
### Previous RA Material { .prev-ra }

* Angola
* Botswana
* Eswatini
* Lesotho
* Namibia
* South Africa
* Zambia
* Zimbabwe
* Malawi
* Mozambique

### Primary Sources for Old Policies {.prim-source}

* Angola
* Botswana
* Eswatini
* Lesotho
* Namibia
* South Africa
* Zambia
* Zimbabwe
* Malawi
* Mozambique



Western Africa {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar} /// inputs in sidebar
-------------------------------------
**Western Africa**
**Regional Manager**

Christin Le

Row
-------------------------------------


### General Country Information {.gen-country}
* Benin
* Burkina Faso
* Cabo Verde
* Ivory Coast
* Gambia
* Ghana
* Guinea
* Guinea-Bissau
* Liberia
* Mali
* Mauritania
* Niger
* Nigeria
* Senegal
* Sierra Leone
* Togo

Row
-------------------------------------
### Previous RA Material { .prev-ra }

* Benin
* Burkina Faso
* Cabo Verde
* Ivory Coast
* Gambia
* Ghana
* Guinea
* Guinea-Bissau
* Liberia
* Mali
* Mauritania
* Niger
* Nigeria
* Senegal
* Sierra Leone
* Togo

### Primary Sources for Old Policies {.prim-source}

* Benin
* Burkina Faso
* Cabo Verde
* Ivory Coast
* Gambia
* Ghana
* Guinea
* Guinea-Bissau
* Liberia
* Mali
* Mauritania
* Niger
* Nigeria
* Senegal
* Sierra Leone
* Togo



Caribbean {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar} /// inputs in sidebar
-------------------------------------
**Caribbean**
**Regional Manager**

Gerardo Samuel Ixcaragua
Gabriel Belmino Freitas
Ewan Lewis

Row
-------------------------------------


### General Country Information {.gen-country}
* Antigua and Barbuda
* Bahamas
* Barbados
* Cuba
* Dominica
* Dominican Republic
* Grenada
* Haiti
* Jamaica
* Saint Kitts and Nevis
* Saint Lucia
* Saint Vincent and the Grenadines
* Trinidad and Tobago

Row
-------------------------------------
### Previous RA Material { .prev-ra }

* Antigua and Barbuda
* Bahamas
* Barbados
* Cuba
* Dominica
* Dominican Republic
* Grenada
* Haiti
* Jamaica
* Saint Kitts and Nevis
* Saint Lucia
* Saint Vincent and the Grenadines
* Trinidad and Tobago

### Primary Sources for Old Policies {.prim-source}

* Antigua and Barbuda
* Bahamas
* Barbados
* Cuba
* Dominica
* Dominican Republic
* Grenada
* Haiti
* Jamaica
* Saint Kitts and Nevis
* Saint Lucia
* Saint Vincent and the Grenadines
* Trinidad and Tobago



Central + North America {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar} /// inputs in sidebar
-------------------------------------
**Central + North America**
**Regional Manager**

Vanja Grujic
Rose Rasty

Row
-------------------------------------


### General Country Information {.gen-country}
* Belize
* Costa Rica
* Canada
* El Salvador
* Guatemala
* Honduras
* Mexico
* Nicaragua
* Panama
* USA

Row
-------------------------------------
### Previous RA Material { .prev-ra }

* Belize
* Costa Rica
* Canada
* El Salvador
* Guatemala
* Honduras
* Mexico
* Nicaragua
* Panama
* USA

### Primary Sources for Old Policies {.prim-source}

* Belize
* Costa Rica
* Canada
* El Salvador
* Guatemala
* Honduras
* Mexico
* Nicaragua
* Panama
* USA



South America {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar} /// inputs in sidebar
-------------------------------------
**South America**
**Regional Manager**

Marcus Torres

Row
-------------------------------------


### General Country Information {.gen-country}
* Argentina
* Bolivia
* Brazil
* Chile
* Colombia
* Ecuador
* Guyana
* Paraguay
* Peru
* Suriname
* Uruguay
* Venezuela

Row
-------------------------------------
### Previous RA Material { .prev-ra }

* Argentina
* Bolivia
* Brazil
* Chile
* Colombia
* Ecuador
* Guyana
* Paraguay
* Peru
* Suriname
* Uruguay
* Venezuela

### Primary Sources for Old Policies {.prim-source}

* Argentina
* Bolivia
* Brazil
* Chile
* Colombia
* Ecuador
* Guyana
* Paraguay
* Peru
* Suriname
* Uruguay
* Venezuela



Eurasia {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar} /// inputs in sidebar
-------------------------------------
**Eurasia**
**Regional Manager**

Caress Schenk

Row
-------------------------------------


### General Country Information {.gen-country}
* Russia
* Ukraine
* Belarus
* Kazakhstan
* Kyrgyzstan
* Tajikistan
* Turkmenistan
* Uzbekistan

Row
-------------------------------------
### Previous RA Material { .prev-ra }

* Russia
* Ukraine
* Belarus
* Kazakhstan
* Kyrgyzstan
* Tajikistan
* Turkmenistan
* Uzbekistan

### Primary Sources for Old Policies {.prim-source}

* Russia
* Ukraine
* Belarus
* Kazakhstan
* Kyrgyzstan
* Tajikistan
* Turkmenistan
* Uzbekistan



East Asia {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar} /// inputs in sidebar
-------------------------------------
**East Asia**
**Regional Manager**

Kelis Wong

Row
-------------------------------------


### General Country Information {.gen-country}
* China
* Hong Kong
* North Korea
* South Korea
* Japan
* Macau
* Mongolia
* Taiwan

Row
-------------------------------------
### Previous RA Material { .prev-ra }

* China
* Hong Kong
* North Korea
* South Korea
* Japan
* Macau
* Mongolia
* Taiwan

### Primary Sources for Old Policies {.prim-source}

* China
* Hong Kong
* North Korea
* South Korea
* Japan
* Macau
* Mongolia
* Taiwan



Southeast Asia {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar} /// inputs in sidebar
-------------------------------------
**Southeast Asia**
**Regional Manager**

Pia Bansagi
Fadhilah F. Primandari

Row
-------------------------------------


### General Country Information {.gen-country}
* Brunei
* Cambodia
* Indonesia
* Laos
* Malaysia
* Myanmar
* Philippines
* Singapore
* Thailand
* Timor Leste
* Vietnam

Row
-------------------------------------
### Previous RA Material { .prev-ra }

* Brunei
* Cambodia
* Indonesia
* Laos
* Malaysia
* Myanmar
* Philippines
* Singapore
* Thailand
* Timor Leste
* Vietnam

### Primary Sources for Old Policies {.prim-source}

* Brunei
* Cambodia
* Indonesia
* Laos
* Malaysia
* Myanmar
* Philippines
* Singapore
* Thailand
* Timor Leste
* Vietnam



South Asia {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar} /// inputs in sidebar
-------------------------------------
**South Asia**
**Regional Manager**

Hanaan Shafi

Row
-------------------------------------


### General Country Information {.gen-country}
* Afghanistan
* Bangladesh
* Bhutan
* India
* Iran
* Maldives
* Nepal
* Pakistan
* Sri Lanka

Row
-------------------------------------
### Previous RA Material { .prev-ra }

* Afghanistan
* Bangladesh
* Bhutan
* India
* Iran
* Maldives
* Nepal
* Pakistan
* Sri Lanka

### Primary Sources for Old Policies {.prim-source}

* Afghanistan
* Bangladesh
* Bhutan
* India
* Iran
* Maldives
* Nepal
* Pakistan
* Sri Lanka



 Middle East {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar} /// inputs in sidebar
-------------------------------------
** Middle East**
**Regional Manager**

Maryam Al-Hammadi

Row
-------------------------------------


### General Country Information {.gen-country}
* Iraq
* Bahrain
* Israel
* Jordan
* Kuwait
* Lebanon
* Northern Cyprus
* Cyprus
* Oman
* Qatar
* Saudi Arabia
* Palestine
* Syria
* Turkey
* United Arab Emirates
* Yemen

Row
-------------------------------------
### Previous RA Material { .prev-ra }

* Iraq
* Bahrain
* Israel
* Jordan
* Kuwait
* Lebanon
* Northern Cyprus
* Cyprus
* Oman
* Qatar
* Saudi Arabia
* Palestine
* Syria
* Turkey
* United Arab Emirates
* Yemen

### Primary Sources for Old Policies {.prim-source}

* Iraq
* Bahrain
* Israel
* Jordan
* Kuwait
* Lebanon
* Northern Cyprus
* Cyprus
* Oman
* Qatar
* Saudi Arabia
* Palestine
* Syria
* Turkey
* United Arab Emirates
* Yemen



Eastern Europe and Western Asia {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar} /// inputs in sidebar
-------------------------------------
**Eastern Europe and Western Asia**
**Regional Manager**

Mayisa

Row
-------------------------------------


### General Country Information {.gen-country}
* Bulgaria
* Czechia
* Hungary
* Slovenia
* Poland
* Republic of Moldova
* Romania
* Slovakia
* Armenia
* Azerbaijan
* Georgia

Row
-------------------------------------
### Previous RA Material { .prev-ra }

* Bulgaria
* Czechia
* Hungary
* Slovenia
* Poland
* Republic of Moldova
* Romania
* Slovakia
* Armenia
* Azerbaijan
* Georgia

### Primary Sources for Old Policies {.prim-source}

* Bulgaria
* Czechia
* Hungary
* Slovenia
* Poland
* Republic of Moldova
* Romania
* Slovakia
* Armenia
* Azerbaijan
* Georgia



Northern Europe {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar} /// inputs in sidebar
-------------------------------------
**Northern Europe**
**Regional Manager**

Klea Vogli

Row
-------------------------------------


### General Country Information {.gen-country}
* Denmark
* Estonia
* Finland
* Iceland
* Latvia
* Lithuania
* Norway
* Sweden
* Netherlands

Row
-------------------------------------
### Previous RA Material { .prev-ra }

* Denmark
* Estonia
* Finland
* Iceland
* Latvia
* Lithuania
* Norway
* Sweden
* Netherlands

### Primary Sources for Old Policies {.prim-source}

* Denmark
* Estonia
* Finland
* Iceland
* Latvia
* Lithuania
* Norway
* Sweden
* Netherlands



Southern Europe {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar} /// inputs in sidebar
-------------------------------------
**Southern Europe**
**Regional Manager**

Noor Altunaiji
Vanja Grujic

Row
-------------------------------------


### General Country Information {.gen-country}
* Albania
* Andorra
* Bosnia and Herzegovina
* Croatia
* Greece
* Malta
* Montenegro
* North Macedonia
* Portugal
* San Marino
* Serbia
* Kosovo
* Vatican
* Spain
* Italy

Row
-------------------------------------
### Previous RA Material { .prev-ra }

* Albania
* Andorra
* Bosnia and Herzegovina
* Croatia
* Greece
* Malta
* Montenegro
* North Macedonia
* Portugal
* San Marino
* Serbia
* Kosovo
* Vatican
* Spain
* Italy

### Primary Sources for Old Policies {.prim-source}

* Albania
* Andorra
* Bosnia and Herzegovina
* Croatia
* Greece
* Malta
* Montenegro
* North Macedonia
* Portugal
* San Marino
* Serbia
* Kosovo
* Vatican
* Spain
* Italy



Western Europe {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar} /// inputs in sidebar
-------------------------------------
**Western Europe**
**Regional Manager**

Paula Ganga

Row
-------------------------------------


### General Country Information {.gen-country}
* Austria
* Belgium 
* France
* Germany
* Liechtenstein
* Luxembourg
* Monaco
* United Kingdom
* Switzerland
* Ireland

Row
-------------------------------------
### Previous RA Material { .prev-ra }

* Austria
* Belgium 
* France
* Germany
* Liechtenstein
* Luxembourg
* Monaco
* United Kingdom
* Switzerland
* Ireland

### Primary Sources for Old Policies {.prim-source}

* Austria
* Belgium 
* France
* Germany
* Liechtenstein
* Luxembourg
* Monaco
* United Kingdom
* Switzerland
* Ireland



Oceania {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar} /// inputs in sidebar
-------------------------------------
**Oceania**
**Regional Manager**

Sarah Edmonds

Row
-------------------------------------


### General Country Information {.gen-country}
* Australia
* New Zealand
* Fiji
* Papua New Guinea
* Solomon Islands
* Vanuatu
* Micronesia
* Kiribati
* Marshall Islands
* Nauru
* Palau
* Samoa
* Tonga
* Tuvalu

Row
-------------------------------------
### Previous RA Material { .prev-ra }

* Australia
* New Zealand
* Fiji
* Papua New Guinea
* Solomon Islands
* Vanuatu
* Micronesia
* Kiribati
* Marshall Islands
* Nauru
* Palau
* Samoa
* Tonga
* Tuvalu

### Primary Sources for Old Policies {.prim-source}

* Australia
* New Zealand
* Fiji
* Papua New Guinea
* Solomon Islands
* Vanuatu
* Micronesia
* Kiribati
* Marshall Islands
* Nauru
* Palau
* Samoa
* Tonga
* Tuvalu


United States {data-navmenu="Country Dashboards"}
===================================== 

Inputs {.sidebar}
-------------------------------------
**Country Managers**

* **Derek Duba**
* **Matthew Cottrell**

Row
-------------------------------------

### General Country Information {.gen-country}

* Alabama
* Alaska
* Arkansas

Row
-------------------------------------
### Previous RA Material { .prev-ra }
* Alabama
* Alaska
* Arkansas


### Primary Sources for Old Policies {.prim-source}
* Alabama
* Alaska
* Arkansas
 
</body>
</html>
