---
title: "CoronaNet Research Assistant Dashboard"
output: 
  flexdashboard::flex_dashboard
    
 # vertical_layout: fill
---

<html>
    <head>
        <meta charset="utf-8">
        <title>MiniPreview Demo</title>

        <style>
        
          /* Set border color of tab to white */
          .nav-tabs-custom > .nav-tabs > li.active {
          border-top-color: white}
                    }
        
         /* Set tab bar to grey */
        .tabset { 
             background-color: grey;
          }
        
          /* Set font color of inactive tab to grey */
              .nav-tabs-custom .nav-tabs > li > a {
                color: grey;
                font-weight: bold;
              } 
              
              /* Set font color of active tab to blue */
              .nav-tabs-custom .nav-tabs > li.active > a {
                color: white;
              } 
              
              .nav-tabs-custom .nav-tabs > li.focus > a {
                color: white;
              } 

              
              /* https://stackoverflow.com/questions/31638845/change-to-a-different-colour-for-each-bootstrap-active-tab-css*/
            .nav-tabs-custom > .nav-tabs > li > a {
                  background: ;
                  border-radius: 8px;
                  margin-right: 8px;
                  box-shadow:0 0 15px #eceefd;
            }
            
            .nav-tabs > li > a {
              background-color: #BE9FF8;
              color: #ffffff;
            }
            .nav-tabs > li.active:nth-child(1) > a {
              background-color: #E8C120;
            }
            .nav-tabs > li.active:nth-child(2) > a {
              background-color: #BE9FF8;
            }
            .nav-tabs > li.active:nth-child(3) > a {
              background-color: #F79488;
            }
            .nav-tabs > li.active:nth-child(4) > a {
              background-color: #3383FF;
            }
            
            .nav-tabs > li.focus:nth-child(1) > a {
              background-color: #FFC700;
            }
            .nav-tabs > li.focus:nth-child(2) > a {
              background-color: #BE9FF8;
            }
            .nav-tabs > li.focus:nth-child(3) > a {
              background-color: #F79488;
            }
            .nav-tabs > li.focus:nth-child(4) > a {
              background-color: #64B2F0;
            }
           
          .chart-wrapper,
          .nav-tabs-custom,
          .sbframe-commentary
          {
            background: ;
            border: 1px solid #e2e2e2;
            border-radius: 15px;
            margin-bottom: 8px;
            margin-right: 8px;
            box-shadow:0 0 15px #eceefd;
          }
          a {
            color: white;
            }
          body{
            font-size: 18px;
            }
   
          .break {
                text-align: center;
            }
            .chart-title {  /* chart_title  */
              font-size: 35px;
              font-weight: bold;
              color: white;
            }
            #tools{
                background-color: #8D41D6;
              }

              
            #organization{
                background-color: #e9533d;
              }
            #communication{
                background-color: #64B2F0;
              }
            
            #coding-resources{
                background-color: #E8C120;
              }
            
        
            #tools-resources{
                background-color: #BE9FF8;
              }
            
            #organization-resources{
                background-color: #F79488;
              }
            
            #ra-repository{
                background-color: #BAF300;
              }
              
          .prev-ra{
            background-color: #8D41D6;
          }
         
          .gen-country{
                background-color: #FFC700;
              }
            
          .prim-source{
                background-color: #BAF300;
              }

          details summary::-webkit-details-marker { 
           display:none;
        } 
        summary{
          color: white;
        }
        
        
        body {
          padding: 75px 100px 50px 100px;
          background-color: white;
          }
        
        </style>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>

        <!-- MiniPreview stuff here -->
        <link href="./jquery.minipreview.css" rel="stylesheet">
        <script src="./jquery.minipreview.js"></script>
        <script>
            $(function() {
                $('#p1 a').miniPreview({ prefetch: 'pageload' });
                $('#p2 a').miniPreview({ prefetch: 'parenthover' });
                $('#p1 a').miniPreview({ prefetch: 'none' });
            });
        </script>
    </head>

<body>


 

Main Dashboard 
===================================== 

Welcome! Pssst... take a look around!

Row 
-------------------------------------
### Tools {data-padding=10}

*  <p id = "p1">
<a href="https://docs.google.com/spreadsheets/d/1lpAsH-aJic9AbJR6YT4-tbwMDp4vCgmS_R-5djCl2f8/edit?usp=sharing">Overton Raw Sources</a>
</p>

* <p id = "p1">
<a href="https://docs.google.com/spreadsheets/d/1X8kzeLJImEimN4TvPscx6RLhZnpo5m9bSZsyVeWRWck/edit?usp=sharing">Policy Checker Sheet</a>
</p>

* Qualtrics Survey

* <p id = "p1">
<a href="https://kubinec.shinyapps.io/corona_validate/">Shiny App</a>
</p>

* <p id = "p1">
<a href="https://docs.google.com/spreadsheets/d/1OuFhdRryq2in6DfvP2PuKoe5zTWf-kgMo3Z-cBkJWcU/edit?usp=sharing">Delete a policy entry</a>
</p>

* [Slack](https://corona-govt-response.slack.com/archives/C010V8MKHK2)

### Organization {data-padding=10}
 
CoronaNet Checklist 

* [Regional Data Checklist](https://docs.google.com/spreadsheets/d/1RL0Go-ULJxSHrFsJcS521Zzdo1j6E-vlWQd72VD4bUM/edit?usp=sharing)
* <details>
  <summary>Country Data Checklist (one subnational region per sheet)</summary>
  <small>
  + [Brazil Data Checklist](https://docs.google.com/spreadsheets/d/1YymUcP1_h5OgMhdIca4I2L0veLGhDdgs3Y5DePH49hI/edit?usp=sharing)
  + [Canada Data Checklist](https://docs.google.com/spreadsheets/d/1zt5atXwIfLcdG1pZQ5m7MsjKyiueAb5Kiada6gHXtbA/edit?usp=sharing)
  + [China Data Checklist](https://docs.google.com/spreadsheets/d/1KbKT7kMLUvALlqeGzw1aDZcWqrp3bIjoA5QYbVddJDM/edit?usp=sharing)
  + [France Data Checklist](https://docs.google.com/spreadsheets/d/1wVa9yES4GWthNJyCFLEENeDeZQNcW0tk3ua16uPzLY8/edit?usp=sharing)
  + [Germany Data Checklist](https://docs.google.com/spreadsheets/d/1SouqfwoZN6uueohxmDZzeWwzENHwAdRP_5KRAYssnfs/edit?usp=sharing)
  + [India Data Checklist](https://docs.google.com/spreadsheets/d/1Wmwb4-I42BpihVmkM-AV5OM0wl1PIQ0Z-4bbDyVpOqg/edit?usp=sharing)
  + [Italy Data Checklist](https://docs.google.com/spreadsheets/d/1tSZXITSuRxpc-qM3fNmjgDfS-vj4bQoHcoZHaao8bC8/edit?usp=sharing)
  + [Japan Data Checklist](https://docs.google.com/spreadsheets/d/1z3bXp8H4SaDPv3AK_cMUAuNryin6GHr4jG94ERTCNkA/edit?usp=sharing)
  + [Nigeria Data Checklist](https://docs.google.com/spreadsheets/d/1eZGkciKp2dBRDxpfVAgF0dQNCEVIiMNNw-2IWtb0EIQ/edit?usp=sharing)
  + [Russia Data Checklist](https://docs.google.com/spreadsheets/d/1BJxOdIjGq9GaHgLV_qxbW4AgwZ3fu3-ID4j-gXPMrhA/edit?usp=sharing)
  + [Spain Data Checklist](https://docs.google.com/spreadsheets/d/1y271IKkpDG50WcbnZsrdMBXPDS75_x1dSdIUW68Ca6A/edit?usp=sharing)
  + [Switzerland Data Checklist](https://docs.google.com/spreadsheets/d/1mBzoxh4F_e-MmNN2u6FU6LhnRstxKDjyvTqAPfabRds/edit?usp=sharing)
  + [United States Data Checklist](https://docs.google.com/spreadsheets/d/16wpRD7_gv3UseLs5fyc7PeDMbcVlYaMDR0IghVsfBIQ/edit?usp=sharing) </small>
</details>


#### Templates


* <p id = "p1">
<a href="https://docs.google.com/document/d/1UCy4Cr59cUlj0Uog6R9NB2DOF8i8ky8sUE48Fq6F_Yw/edit#"> Country Overview Template </a>
</p>

* <p id = "p1">
<a href="https://docs.google.com/spreadsheets/d/1wV_4QOjK0QFddz6j7jMczyXA9I3uzSU1kWAlIX6Zslg/edit#gid=14819459"> Timeline Template </a>
</p>

Row {.tabset}
-------------------------------------


### Coding Resources


#### How to ...
* <details>
  <summary>Assess the policies in your country</summary>
  <small>
   + Check out the guidelines in the [Country Overview Template](https://docs.google.com/document/d/1UCy4Cr59cUlj0Uog6R9NB2DOF8i8ky8sUE48Fq6F_Yw/edit#)
   + Check out the resources left by the previous RAs in your relevant regional/country dashboard
   + Find relevant policies in the [Overton Raw Sources Sheet](https://docs.google.com/spreadsheets/d/1lpAsH-aJic9AbJR6YT4-tbwMDp4vCgmS_R-5djCl2f8/edit?usp=sharing) 
   + Find relevant policies in the [Policy Checker Sheet](https://docs.google.com/spreadsheets/d/1jNeDVVE_faOVRLfW884nfTcMRkHM9qhYwtcnG2VpZnk/edit#gid=612528935)
  </small>
</details>

* <details>
  <summary>Make a plan for coding</summary>
  <small>
   + Use the [Timeline Template](https://docs.google.com/spreadsheets/d/1wV_4QOjK0QFddz6j7jMczyXA9I3uzSU1kWAlIX6Zslg/edit#gid=14819459)
  </small>
</details>

* <details>
  <summary>Get started with coding</summary> 
  <small>
    + The [CoronaNet Coding Guide](https://www.coronanet-project.org/coding_guide.html) provides helpful guidance on how to do updates, corrections and differences between different policy types
  + The [CoronaNet Data Collection Guidelines and Codebook](https://docs.google.com/document/d/1zvNMpwj0onFvUZ_gLl4RRjqS-clbHv3TIX6EOHofsME/edit) provides helpful written guidance on how to enter policies into Qualtrics
  + [The General Training Video](https://nyu.zoom.us/rec/play/9NyJ1dYJ88tK3fLwYVH3FNXLkbWdbI9P2guAkYFYWGalDMHYYhVnNcFiCg7ZnuKAyGoOqGYPc_OJp6DM.St4xWFlsIjQL7arN?continueMode=true) provides helpful verbal and visual guidance for how to enter policies into Qualtrics 
  + [Video on how to do updates](https://tum-conf.zoom.us/rec/play/vJF5fuGop243GdyQsQSDC_QqW426KaOshHMfqaBZnhrnViIBO1PzZ-QaZbPBtptgnr6hozgzRfrwne6q?startTime=1588513802000) <small>(Password: 7C&*60@= )</small></small>
</details>

* <details>

  <summary>Clean policies in your country</summary> 
  +   <small>Fill out your respective [Regional Checklist](https://docs.google.com/spreadsheets/d/1RL0Go-ULJxSHrFsJcS521Zzdo1j6E-vlWQd72VD4bUM/edit?usp=sharing) or Country Checklists</small>
</details>

* <details>
  <summary>Get help with assessing, planning, coding and cleaning the data for your region! </summary>
  <small>
   Don't hesitate to ask questions! If you have them you can...
   1. Refer to the [Codebook](https://docs.google.com/document/d/1zvNMpwj0onFvUZ_gLl4RRjqS-clbHv3TIX6EOHofsME/edit?usp=sharing) for variable definitions
   2. Check out the FAQ in the [Shiny App](https://kubinec.shinyapps.io/corona_validate/)! It is updated weekly with the most common questions posed on #ra-chat
   3. Don't see your question there? Post it in the [#ra-chat](https://corona-govt-response.slack.com/archives/C010V8MKHK2) channel.
   4.  Reach out to your regional mangager, hogwarts channel or fellow RAs for advice
  </small>
</details>
<br/>




#### General Resources

*
<details>
  <summary> October 1 Training video  </summary>
  <small>
   In this [Oct 1 Training Video](https://tum-conf.zoom.us/rec/share/qnbb_bzGMllKWYqEb6IqE_498K_V902RYPE5bo78v11S8Wp-3dmR5l-zT2JQHA-O.zHDV3DOhsmw0dxgv) <small>  (Passcode: f5G6^AY7)</small> we go over the rationale for assessing, planning, coding and cleaning. We also provide an overview of the new tools available on this dashboard in order to do so, including the :
   * [Country Overview Template](https://docs.google.com/document/d/1UCy4Cr59cUlj0Uog6R9NB2DOF8i8ky8sUE48Fq6F_Yw/edit#)
   * [Country Timeline](https://docs.google.com/spreadsheets/d/1wV_4QOjK0QFddz6j7jMczyXA9I3uzSU1kWAlIX6Zslg/edit#gid=14819459), 
   * [Coding Guide](https://www.coronanet-project.org/coding_guide.html), the ['printed' survey questions](https://www.coronanet-project.org/survey) ;
   *  and the data checklists, 
  
  </small>
</details>


*
<details>
  <summary> CoronaNet Manual </summary>
  <small>
   This is the 'Bible' of the CoronaNet Project
   * You can learn about all the different parts of the project in detail from [reading the Manual](https://www.coronanet-project.org/Manual).
  </small>
</details>
<br/>

### Tools Resources

#### Overton Raw Sources
* <details>
  <summary>How to use the Overton Raw Sources</summary>
  <small>

  Overton is a company which collects government documents from around the world and which has generously allowed us to access to raw government documents related to COVID-19.

  * To find relevant documents for your country, please click on the corresponding URL in the 'Country List' front page of the Overton Raw Sources sheet. 

  * The documents listed in the Overton Raw Sources sheet are scraped from the Overton site. They provide a useful reference point for:
      + Checking whether all government policies related to COVID-19 in your country are coded.
      + Providing additional sources for where to find information about COVID-19 polcies in a particular country. If it is not already noted, feel free to note such sources in the relevant 'General Country Information' link found in your respective regional or country dashbbaord. 
   * The Overton Raw Sources sheet will be updated weekly. 
   * Caveats: 
      +  Note that the list provided by Overton is not a definitive list of all COVID-19 related policies but provide a strong foundation for finding and verifying the existence of COVID-19 policies in a particular country. 
      + Note that not all documents listed in the Overton Raw Sources sheet may be relevant to code for the CoronaNet Project. 
      + In addition note Overton does not cover all countries. 

  </small>
</details>

#### Policy Checker Sheet

* <details>
  <summary> How to Use the Policy Checker Sheet</summary>
  <small>

  The Policy Checker Sheet checks the CoronaNet data against the WHO PHSM Dataset. The sheet will be updated semi-regularly as the WHO PHSM dataset itself is updated. 

  * The sheet is organized by region and policy type, with one sheet per region

   * Caveats: 
      +  Note that WHO PHSM dataset does not provide definitive list of all COVID-19 related policies but provide a strong foundation for finding and verifying the existence of COVID-19 policies in a particular country. 
      + Note that it is possible that some policies in the Policy Checker Sheet is miscoded. For example, a policy listed in the 'Quarantine' tab, may actually be about 'Lockdown' and not quarantine. In these cases, please code the policy that makes sense for the CoronaNet database, not what is indicated in the Policy Checker Sheet. 

  </small>
</details>


#### Qualtrics Survey

* <details>
  <summary>How to access the Qualtrics Survey</summary>
  <small>

   * You will receive access to the Qualtrics survey after having passed the training test and filling out the committment form
   * Every RA receives a personalized link to the Qualtrics survey
   * Please contact admin@coronanet-project.org if you have not recieved access to the survey (note, there may be a lag of a few days before you receive access)
  </small>
</details>

* <details>
  <summary>What's in the Qualtrics Survey? </summary>
  <small>
   * Take a look through the questions in the [Qualtrics survey](https://www.coronanet-project.org/survey)
   * Search through the [codebook](https://docs.google.com/document/d/1zvNMpwj0onFvUZ_gLl4RRjqS-clbHv3TIX6EOHofsME/edit?usp=sharing) for the variable definitions 
   * Get an overview of all the different [policy types and sub-types](https://docs.google.com/spreadsheets/d/10XiTrBSOJkJvCW0lYt2W6MJo3CCLANjvMjIG4RuOd6Q/edit?usp=sharing)
  </small>
</details>


#### Shiny App
* <details>
  <summary>How to Access the Shiny App</summary>
  <small>
  
    * You need an email invitation to access the Shiny App
    * Check your spam folders for such an invitation
    * If you have never received an invitation, post in the #record-tracker app and someone will add you
      </small>
</details>

* <details>
  <summary>How to use the Shiny App</summary>
<small>
  + <p id = "p1">
<a href= "https://youtu.be/f-ex3_4luu4">Use the Shiny App for filling out the data checklist</a>
</p> 

  + <p id = "p1">
<a href= "https://docs.google.com/document/d/1MgZ5KSll-KGRlIJEot6j-SOgLac8C5og_3K5S_nAYZA/edit?usp=sharing">
Text and Screenshots</a>
  + You can also use the Shiny App for making corrections. Note that it takes 24 hours for the corrections to enter into the database. 
</p> 

  </small>
</details>


* <details>
  <summary>What else is on Shiny App?</summary>
    * Check out the FAQs on the Shiny App for a summary of the questions asked on #ra-chat!
</details>

<br/>

#### Delete a Policy

* <details>
  <summary>When to delete a policy</summary>
  <small>
   * There are duplicate policies
   * It is easier to delete a policy and start over than to correct it
   * The policy does not belong in the dataset
</small>
</details>

#### Slack

* <details>
  <summary>What is Slack? </summary>
  <small>
   * Slack is the main tool that CoronaNet members use to communicate with each other
   * Explore different functionalities in Slack [here!](https://www.coronanet-project.org/Manual#Slack) 
   * Aside from your regional or country channel, the most relevant channels in slack are [#ra-chat](https://corona-govt-response.slack.com/archives/C010V8MKHK2) (where you can ask all your coding questions), [#random](https://corona-govt-response.slack.com/archives/C010PMHE2J3) (where you can participate in weekly Hogwarts contests), [#ra-suggestions](https://corona-govt-response.slack.com/archives/C011KCG2JD6) (where you can provide suggestions for how to improve the Qualtrics survey), and [#general](https://corona-govt-response.slack.com/archives/C010PHG8V3Q) (where you can get and post general information of general interst)
</small>
</details>


### Organization Resources

* <details>
  <summary>How to fill out the Regional/Country Data Checklist  </summary>
  <small>
   * The data checklists are an important tool to raise the quality of the data and to track the progress of the data over time. Our current goal is **to have all the data complete and clean until October 1, 2020 by January 1, 2020** and the data checklist will be important for helping us get there! Please see below for: 
      +  [Video on how to use the data checklist](https://tum-conf.zoom.us/rec/share/gyGEk0OOn0U3Q_ppE9u-_mAe_5dqcDany19OfLCdcOAs3pYOrygYYDZD0IK2PF-j.66KrNjLYx4TTn1A1) <small> Passcode: tCQ0%8wC </small>
</small>
</details>


#### Templates
* <details>
  <summary>How to fill out the Country Overview  </summary>
  <small>
   * The country overview will help you assess the policies in your region before you code! See below for 
      +  [A Video on how to make a country overview](https://www.youtube.com/watch?v=NUbNkip-Yyw) 
</small>
</details>


* <details>
  <summary>How to use the Timeline Template   </summary>
  <small>
   * The timeline template will help you plan how to code the policies in your region before you code! See below for 
      +  [A Video on how to make a timeline template](https://youtu.be/vbZZ8WgNEKQ) 
</small>
</details>



### Communication

#### Within the Project
* [Weekly General Meeting--- Join us Wednesdays at 4:30pm CET!](https://tum-conf.zoom.us/j/94054314336)  <small>  (Password: 599952)</small>  
* [Come hang out in the Community Hangout Room](https://tum-conf.zoom.us/j/92401524948) <small>  (Password: 12345)  </small>  

 <br> 


#### Our public profile
* [Follow the CoronaNet Twitter Feed](https://twitter.com/CoronaNet_org)  
*  <p id = "p1"><a href= "https://www.linkedin.com/groups/8982369/"> Connect to CoronaNet on LinkedIn </a>
</p>
*  <p id = "p1"><a href= "https://www.coronanet-project.org/ra_call.html"> Invite others to join CoronaNet! </a>
</p>
* [Check out the public CoronaNet webpage](https://www.coronanet-project.org)

 <br> 
 
<details>
  <summary>Saying goodbye? Before you go...</summary>
  
    1. Please make sure to contact your regional manager to let them know that you'll be leaving
  2. <details><summary> Make sure you fill out an Exit Report before you go! </summary> <small>
      +   The [exit report](https://docs.google.com/document/d/1TBlRXb3yGuFyA45JomTxqrPCkAvI9W_D4Ah75PKLgNI/edit?usp=sharing) is important to pass on information so that the next RA has a better idea of what's going on in your region and what should be done (see this [short video](https://youtu.be/i8qoqNi5iEk) for more instructions). You can **upload it to your relevant country/sub-national region folder**
      + For regional and country managers, we have created a [regional](https://docs.google.com/document/d/1RTikALjGQ_-EYDFAWbNybnuW30xBK9259JIcICYMXZY/edit#) and [country manager](https://docs.google.com/document/d/1XLb-EhLJQ8OH_EX8ng1bA-UYDWL4IjagMncEolGkOUI/edit#) exit report template which we hope you will fill out and pass on to the next regional or country manager to fill your position!
      +  If you have **other any useful information about your country** that you would like to pass on, please remember to **upload them to your relevant country/sub-national region folder** so that the new RA can access them under 'Previous RA Material'. </small> </details>
  3. Lastly, please fill out this  [exit survey](https://docs.google.com/forms/d/e/1FAIpQLSc-yn3BuPxSBx-wskp_0gocPYWP2BVtvf1BMtrdP_I7HblRSw/viewform) to let us know about your experience with us and how we can do better! 

</details>

Northern Africa {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Northern Africa**
**Regional Manager**

Naela Elmore

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------


### General Country Information {.gen-country}
* Algeria
* Egypt
* Libya
* Morocco
* Sudan
* Tunisia

Row
-------------------------------------
### RA Materials { .prev-ra }

* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Algeria">Algeria</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Egypt">Egypt</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Libya">Libya</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Morocco">Morocco</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Sudan">Sudan</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Tunisia">Tunisia</a>

### Primary Sources for Old Policies {.prim-source}

* Algeria
* Egypt
* Libya
* Morocco
* Sudan
* Tunisia



Eastern Africa {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Eastern Africa**
**Regional Manager**

Sanjana Jain

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------


### General Country Information {.gen-country}
* Burundi
* Comoros
* Djibouti
* Eritrea
* Ethiopia
* Kenya
* Madagascar
* Mauritius
* Rwanda
* Seychelles
* Somalia
* South Sudan
* Uganda
* Tanzania

Row
-------------------------------------
### RA Materials { .prev-ra }

* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Burundi">Burundi</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Comoros">Comoros</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Djibouti">Djibouti</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Eritrea">Eritrea</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Ethiopia">Ethiopia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Kenya">Kenya</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Madagascar">Madagascar</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Mauritius">Mauritius</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Rwanda">Rwanda</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Seychelles">Seychelles</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Somalia">Somalia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/South%20Sudan">South Sudan</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Uganda">Uganda</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Tanzania">Tanzania</a>

### Primary Sources for Old Policies {.prim-source}

* Burundi
* Comoros
* Djibouti
* Eritrea
* Ethiopia
* Kenya
* Madagascar
* Mauritius
* Rwanda
* Seychelles
* Somalia
* South Sudan
* Uganda
* Tanzania



Central Africa {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Central Africa**
**Regional Managers**

Ryan Kim
Elif Çalışkan

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------


### General Country Information {.gen-country}
* Cameroon
* Central African Republic
* Chad
* Republic of the Congo
* Democratic Republic of the Congo
* Equatorial Guinea
* Gabon
* Sao Tome and Principe

Row
-------------------------------------
### RA Materials { .prev-ra }

* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Cameroon">Cameroon</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Central%20African%20Republic">Central African Republic</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Chad">Chad</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Republic%20of%20the%20Congo">Republic of the Congo</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Democratic%20Republic%20of%20the%20Congo">Democratic Republic of the Congo</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Equatorial%20Guinea">Equatorial Guinea</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Gabon">Gabon</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Sao%20Tome%20and%20Principe">Sao Tome and Principe</a>

### Primary Sources for Old Policies {.prim-source}

* Cameroon
* Central African Republic
* Chad
* Republic of the Congo
* Democratic Republic of the Congo
* Equatorial Guinea
* Gabon
* Sao Tome and Principe



Southern Africa {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Southern Africa**
**Regional Manager**

Klea Vogli & Mia Balice

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------


### General Country Information {.gen-country}
* Angola
* Botswana
* Eswatini
* Lesotho
* Namibia
* South Africa
* Zambia
* Zimbabwe
* Malawi
* Mozambique

Row
-------------------------------------
### RA Materials { .prev-ra }

* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Angola">Angola</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Botswana">Botswana</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Eswatini">Eswatini</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Lesotho">Lesotho</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Namibia">Namibia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/South%20Africa">South Africa</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Zambia">Zambia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Zimbabwe">Zimbabwe</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Malawi">Malawi</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Mozambique">Mozambique</a>

### Primary Sources for Old Policies {.prim-source}

* Angola
* Botswana
* Eswatini
* Lesotho
* Namibia
* South Africa
* Zambia
* Zimbabwe
* Malawi
* Mozambique



Western Africa {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Western Africa**
**Regional Manager**

Christin Le

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------


### General Country Information {.gen-country}
* Benin
* Burkina Faso
* Cabo Verde
* Ivory Coast
* Gambia
* Ghana
* Guinea
* Guinea-Bissau
* Liberia
* Mali
* Mauritania
* Niger
* Nigeria
* Senegal
* Sierra Leone
* Togo

Row
-------------------------------------
### RA Materials { .prev-ra }

* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Benin">Benin</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Burkina%20Faso">Burkina Faso</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Cabo%20Verde">Cabo Verde</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Ivory%20Coast">Ivory Coast</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Gambia">Gambia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Ghana">Ghana</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Guinea">Guinea</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Guinea-Bissau">Guinea-Bissau</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Liberia">Liberia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Mali">Mali</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Mauritania">Mauritania</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Niger">Niger</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Nigeria">Nigeria</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Senegal">Senegal</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Sierra%20Leone">Sierra Leone</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Togo">Togo</a>

### Primary Sources for Old Policies {.prim-source}

* Benin
* Burkina Faso
* Cabo Verde
* Ivory Coast
* Gambia
* Ghana
* Guinea
* Guinea-Bissau
* Liberia
* Mali
* Mauritania
* Niger
* Nigeria
* Senegal
* Sierra Leone
* Togo



Caribbean {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Caribbean**
**Regional Managers**

Gerardo Samuel Ixcaragua
Gabriel Belmino Freitas
Ewan Lewis

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------


### General Country Information {.gen-country}
* Antigua and Barbuda
* Bahamas
* Barbados
* Cuba
* Dominica
* Dominican Republic
* Grenada
* Haiti
* Jamaica
* Saint Kitts and Nevis
* Saint Lucia
* Saint Vincent and the Grenadines
* Trinidad and Tobago

Row
-------------------------------------
### RA Materials { .prev-ra }

* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Antigua%20and%20Barbuda">Antigua and Barbuda</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Bahamas">Bahamas</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Barbados">Barbados</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Cuba">Cuba</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Dominica">Dominica</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Dominican%20Republic">Dominican Republic</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Grenada">Grenada</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Haiti">Haiti</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Jamaica">Jamaica</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Saint%20Kitts%20and%20Nevis">Saint Kitts and Nevis</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Saint%20Lucia">Saint Lucia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Saint%20Vincent%20and%20the%20Grenadines">Saint Vincent and the Grenadines</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Trinidad%20and%20Tobago">Trinidad and Tobago</a>

### Primary Sources for Old Policies {.prim-source}

* Antigua and Barbuda
* Bahamas
* Barbados
* Cuba
* Dominica
* Dominican Republic
* Grenada
* Haiti
* Jamaica
* Saint Kitts and Nevis
* Saint Lucia
* Saint Vincent and the Grenadines
* Trinidad and Tobago



Central + North America {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Central + North America**
**Regional Managers**

Vanja Grujic
Rose Rasty

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------


### General Country Information {.gen-country}
* Belize
* Costa Rica
* Canada
* El Salvador
* Guatemala
* Honduras
* Mexico
* Nicaragua
* Panama
* USA

Row
-------------------------------------
### RA Materials { .prev-ra }

* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Belize">Belize</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Costa%20Rica">Costa Rica</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Canada">Canada</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/El%20Salvador">El Salvador</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Guatemala">Guatemala</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Honduras">Honduras</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Mexico">Mexico</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Nicaragua">Nicaragua</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Panama">Panama</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/USA">USA</a>

### Primary Sources for Old Policies {.prim-source}

* Belize
* Costa Rica
* Canada
* El Salvador
* Guatemala
* Honduras
* Mexico
* Nicaragua
* Panama
* USA



South America {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**South America**
**Regional Manager**

Marcus Torres

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------


### General Country Information {.gen-country}
* Argentina
* Bolivia
* Brazil
* Chile
* Colombia
* Ecuador
* Guyana
* Paraguay
* Peru
* Suriname
* Uruguay
* Venezuela

Row
-------------------------------------
### RA Materials { .prev-ra }

* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Argentina">Argentina</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Bolivia">Bolivia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Brazil">Brazil</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Chile">Chile</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Colombia">Colombia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Ecuador">Ecuador</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Guyana">Guyana</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Paraguay">Paraguay</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Peru">Peru</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Suriname">Suriname</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Uruguay">Uruguay</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Venezuela">Venezuela</a>

### Primary Sources for Old Policies {.prim-source}

* Argentina
* Bolivia
* Brazil
* Chile
* Colombia
* Ecuador
* Guyana
* Paraguay
* Peru
* Suriname
* Uruguay
* Venezuela



Eurasia {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Eurasia**
**Regional Manager**

Caress Schenk

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------


### General Country Information {.gen-country}
* Russia
* Ukraine
* Belarus
* Kazakhstan
* Kyrgyzstan
* Tajikistan
* Turkmenistan
* Uzbekistan

Row
-------------------------------------
### RA Materials { .prev-ra }

* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Russia">Russia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Ukraine">Ukraine</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Belarus">Belarus</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Kazakhstan">Kazakhstan</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Kyrgyzstan">Kyrgyzstan</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Tajikistan">Tajikistan</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Turkmenistan">Turkmenistan</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Uzbekistan">Uzbekistan</a>

### Primary Sources for Old Policies {.prim-source}

* Russia
* Ukraine
* Belarus
* Kazakhstan
* Kyrgyzstan
* Tajikistan
* Turkmenistan
* Uzbekistan



East Asia {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**East Asia**
**Regional Manager**

Kelis Wong

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------


### General Country Information {.gen-country}
* China
* Hong Kong
* North Korea
* South Korea
* Japan
* Macau
* Mongolia
* Taiwan

Row
-------------------------------------
### RA Materials { .prev-ra }

* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/China">China</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Hong%20Kong">Hong Kong</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/North%20Korea">North Korea</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/South%20Korea">South Korea</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Japan">Japan</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Macau">Macau</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Mongolia">Mongolia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Taiwan">Taiwan</a>

### Primary Sources for Old Policies {.prim-source}

* China
* Hong Kong
* North Korea
* South Korea
* Japan
* Macau
* Mongolia
* Taiwan



Southeast Asia {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Southeast Asia**
**Regional Managers**

Pia Bansagi
Fadhilah F. Primandari

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------


### General Country Information {.gen-country}
* Brunei
* Cambodia
* Indonesia
* Laos
* Malaysia
* Myanmar
* Philippines
* Singapore
* Thailand
* Timor Leste
* Vietnam

Row
-------------------------------------
### RA Materials { .prev-ra }

* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Brunei">Brunei</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Cambodia">Cambodia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Indonesia">Indonesia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Laos">Laos</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Malaysia">Malaysia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Myanmar">Myanmar</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Philippines">Philippines</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Singapore">Singapore</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Thailand">Thailand</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Timor%20Leste">Timor Leste</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Vietnam">Vietnam</a>

### Primary Sources for Old Policies {.prim-source}

* Brunei
* Cambodia
* Indonesia
* Laos
* Malaysia
* Myanmar
* Philippines
* Singapore
* Thailand
* Timor Leste
* Vietnam



South Asia {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**South Asia**
**Regional Manager**

Hanaan Shafi

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------


### General Country Information {.gen-country}
* Afghanistan
* Bangladesh
* Bhutan
* India
* Iran
* Maldives
* Nepal
* Pakistan
* Sri Lanka

Row
-------------------------------------
### RA Materials { .prev-ra }

* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Afghanistan">Afghanistan</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Bangladesh">Bangladesh</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Bhutan">Bhutan</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/India">India</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Iran">Iran</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Maldives">Maldives</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Nepal">Nepal</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Pakistan">Pakistan</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Sri%20Lanka">Sri Lanka</a>

### Primary Sources for Old Policies {.prim-source}

* Afghanistan
* Bangladesh
* Bhutan
* India
* Iran
* Maldives
* Nepal
* Pakistan
* Sri Lanka



Middle East {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Middle East**
**Regional Manager**

Maryam Al-Hammadi

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------


### General Country Information {.gen-country}
* Iraq
* Bahrain
* Israel
* Jordan
* Kuwait
* Lebanon
* Northern Cyprus
* Cyprus
* Oman
* Qatar
* Saudi Arabia
* Palestine
* Syria
* Turkey
* United Arab Emirates
* Yemen

Row
-------------------------------------
### RA Materials { .prev-ra }

* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Iraq">Iraq</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Bahrain">Bahrain</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Israel">Israel</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Jordan">Jordan</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Kuwait">Kuwait</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Lebanon">Lebanon</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Northern%20Cyprus">Northern Cyprus</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Cyprus">Cyprus</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Oman">Oman</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Qatar">Qatar</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Saudi%20Arabia">Saudi Arabia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Palestine">Palestine</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Syria">Syria</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Turkey">Turkey</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/United%20Arab%20Emirates">United Arab Emirates</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Yemen">Yemen</a>

### Primary Sources for Old Policies {.prim-source}

* Iraq
* Bahrain
* Israel
* Jordan
* Kuwait
* Lebanon
* Northern Cyprus
* Cyprus
* Oman
* Qatar
* Saudi Arabia
* Palestine
* Syria
* Turkey
* United Arab Emirates
* Yemen



Eastern Europe and Western Asia {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Eastern Europe and Western Asia**
**Regional Manager**

Mayisa

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------


### General Country Information {.gen-country}
* Bulgaria
* Czechia
* Hungary
* Slovenia
* Poland
* Republic of Moldova
* Romania
* Slovakia
* Armenia
* Azerbaijan
* Georgia

Row
-------------------------------------
### RA Materials { .prev-ra }

* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Bulgaria">Bulgaria</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Czechia">Czechia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Hungary">Hungary</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Slovenia">Slovenia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Poland">Poland</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Republic%20of%20Moldova">Republic of Moldova</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Romania">Romania</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Slovakia">Slovakia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Armenia">Armenia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Azerbaijan">Azerbaijan</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Georgia">Georgia</a>

### Primary Sources for Old Policies {.prim-source}

* Bulgaria
* Czechia
* Hungary
* Slovenia
* Poland
* Republic of Moldova
* Romania
* Slovakia
* Armenia
* Azerbaijan
* Georgia



Northern Europe {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Northern Europe**
**Regional Manager**

Klea Vogli

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------


### General Country Information {.gen-country}
* Denmark
* Estonia
* Finland
* Iceland
* Latvia
* Lithuania
* Norway
* Sweden
* Netherlands

Row
-------------------------------------
### RA Materials { .prev-ra }

* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Denmark">Denmark</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Estonia">Estonia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Finland">Finland</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Iceland">Iceland</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Latvia">Latvia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Lithuania">Lithuania</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Norway">Norway</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Sweden">Sweden</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Netherlands">Netherlands</a>

### Primary Sources for Old Policies {.prim-source}

* Denmark
* Estonia
* Finland
* Iceland
* Latvia
* Lithuania
* Norway
* Sweden
* Netherlands



Southern Europe {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Southern Europe**
**Regional Managers**

Noor Altunaiji
Vanja Grujic

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------


### General Country Information {.gen-country}
* Albania
* Andorra
* Bosnia and Herzegovina
* Croatia
* Greece
* Malta
* Montenegro
* North Macedonia
* Portugal
* San Marino
* Serbia
* Kosovo
* Vatican
* Spain
* Italy

Row
-------------------------------------
### RA Materials { .prev-ra }

* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Albania">Albania</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Andorra">Andorra</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Bosnia%20and%20Herzegovina">Bosnia and Herzegovina</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Croatia">Croatia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Greece">Greece</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Malta">Malta</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Montenegro">Montenegro</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/North%20Macedonia">North Macedonia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Portugal">Portugal</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/San%20Marino">San Marino</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Serbia">Serbia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Kosovo">Kosovo</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Vatican">Vatican</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Spain">Spain</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Italy">Italy</a>

### Primary Sources for Old Policies {.prim-source}

* Albania
* Andorra
* Bosnia and Herzegovina
* Croatia
* Greece
* Malta
* Montenegro
* North Macedonia
* Portugal
* San Marino
* Serbia
* Kosovo
* Vatican
* Spain
* Italy



Western Europe {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Western Europe**
**Regional Manager**

Paula Ganga

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------


### General Country Information {.gen-country}
* Austria
* Belgium
* France
* Germany
* Liechtenstein
* Luxembourg
* Monaco
* United Kingdom
* Switzerland
* Ireland

Row
-------------------------------------
### RA Materials { .prev-ra }

* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Austria">Austria</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Belgium">Belgium</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/France">France</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Germany">Germany</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Liechtenstein">Liechtenstein</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Luxembourg">Luxembourg</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Monaco">Monaco</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/United%20Kingdom">United Kingdom</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Switzerland">Switzerland</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Ireland">Ireland</a>

### Primary Sources for Old Policies {.prim-source}

* Austria
* Belgium
* France
* Germany
* Liechtenstein
* Luxembourg
* Monaco
* United Kingdom
* Switzerland
* Ireland



Oceania {data-navmenu="Regional Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Oceania**
**Regional Manager**

Sarah Edmonds

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------


### General Country Information {.gen-country}
* Australia
* New Zealand
* Fiji
* Papua New Guinea
* Solomon Islands
* Vanuatu
* Micronesia
* Kiribati
* Marshall Islands
* Nauru
* Palau
* Samoa
* Tonga
* Tuvalu

Row
-------------------------------------
### RA Materials { .prev-ra }

* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Australia">Australia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/New%20Zealand">New Zealand</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Fiji">Fiji</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Papua%20New%20Guinea">Papua New Guinea</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Solomon%20Islands">Solomon Islands</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Vanuatu">Vanuatu</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Micronesia">Micronesia</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Kiribati">Kiribati</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Marshall%20Islands">Marshall Islands</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Nauru">Nauru</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Palau">Palau</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Samoa">Samoa</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Tonga">Tonga</a>
* <a href="https://github.com/cindyyawencheng/coronanet_ra/tree/master/Tuvalu">Tuvalu</a>

### Primary Sources for Old Policies {.prim-source}

* Australia
* New Zealand
* Fiji
* Papua New Guinea
* Solomon Islands
* Vanuatu
* Micronesia
* Kiribati
* Marshall Islands
* Nauru
* Palau
* Samoa
* Tonga
* Tuvalu

Brazil {data-navmenu="Country Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Country Manager**

* **Danny Downes**

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------

### General Country Information {.gen-country}

* Acre
* Alagoas
* Amapa
* Amazonas
* Bahia
* Ceara
* Espirito Santo
* Federal District
* Goias
* Maranhao
* Mato Grosso
* Mato Grosso do Sul
* Minas Gerais
* Para
* Paraiba
* Parana
* Pernambuco
* Piaui
* Rio de Janeiro
* Rio Grande do Norte
* Rio Grande do Sul
* Rondonia
* Roraima
* Santa Catarina
* Sao Paulo
* Sergipe
* Tocantins

Row
-------------------------------------
### RA Materials { .prev-ra }
* Acre
* Alagoas
* Amapa
* Amazonas
* Bahia
* Ceara
* Espirito Santo
* Federal District
* Goias
* Maranhao
* Mato Grosso
* Mato Grosso do Sul
* Minas Gerais
* Para
* Paraiba
* Parana
* Pernambuco
* Piaui
* Rio de Janeiro
* Rio Grande do Norte
* Rio Grande do Sul
* Rondonia
* Roraima
* Santa Catarina
* Sao Paulo
* Sergipe
* Tocantins

### Primary Sources for Old Policies {.prim-source}
* Acre
* Alagoas
* Amapa
* Amazonas
* Bahia
* Ceara
* Espirito Santo
* Federal District
* Goias
* Maranhao
* Mato Grosso
* Mato Grosso do Sul
* Minas Gerais
* Para
* Paraiba
* Parana
* Pernambuco
* Piaui
* Rio de Janeiro
* Rio Grande do Norte
* Rio Grande do Sul
* Rondonia
* Roraima
* Santa Catarina
* Sao Paulo
* Sergipe
* Tocantins

Italy {data-navmenu="Country Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Country Manager**

* **Bruno Ciccarini**

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------

### General Country Information {.gen-country}

* Abruzzo
* Aosta Valley
* Apulia
* Basilicate
* Calabria
* Campania
* Emilia-Romagna
* Friuli Venezia Giulia
* Latium
* Liguria
* Lombardy
* Molise
* Piedmont
* Sardinia
* Sicily
* The Marches
* Trentino-Alto Adige
* Tuscany
* Umbria
* Veneto

Row
-------------------------------------
### RA Materials { .prev-ra }
* Abruzzo
* Aosta Valley
* Apulia
* Basilicate
* Calabria
* Campania
* Emilia-Romagna
* Friuli Venezia Giulia
* Latium
* Liguria
* Lombardy
* Molise
* Piedmont
* Sardinia
* Sicily
* The Marches
* Trentino-Alto Adige
* Tuscany
* Umbria
* Veneto

### Primary Sources for Old Policies {.prim-source}
* Abruzzo
* Aosta Valley
* Apulia
* Basilicate
* Calabria
* Campania
* Emilia-Romagna
* Friuli Venezia Giulia
* Latium
* Liguria
* Lombardy
* Molise
* Piedmont
* Sardinia
* Sicily
* The Marches
* Trentino-Alto Adige
* Tuscany
* Umbria
* Veneto

India {data-navmenu="Country Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Country Managers**

* **Shubham Thosar**
* **Jay Patel**

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------

### General Country Information {.gen-country}

* Andaman and Nicobar
* Andhra Pradesh
* Arunachal Pradesh
* Assam
* Bihar
* Chandigarh
* Chhattisgarh
* Dadra and Nagar Haveli
* Daman and Diu
* Delhi
* Goa
* Gujarat
* Haryana
* Himachal Pradesh
* Jammu and Kashmir
* Jharkhand
* Karnataka
* Kerala
* Laccadives
* Ladakh
* Madhya Pradesh
* Maharashtra
* Manipur
* Meghalaya
* Mizoram
* Nagaland
* Odisha
* Puducherry
* Punjab
* Rajasthan
* Sikkim
* Tamil Nadu
* Telangana
* Tripura
* Uttar Pradesh
* Uttarakhand
* West Bengal

Row
-------------------------------------
### RA Materials { .prev-ra }
* Andaman and Nicobar
* Andhra Pradesh
* Arunachal Pradesh
* Assam
* Bihar
* Chandigarh
* Chhattisgarh
* Dadra and Nagar Haveli
* Daman and Diu
* Delhi
* Goa
* Gujarat
* Haryana
* Himachal Pradesh
* Jammu and Kashmir
* Jharkhand
* Karnataka
* Kerala
* Laccadives
* Ladakh
* Madhya Pradesh
* Maharashtra
* Manipur
* Meghalaya
* Mizoram
* Nagaland
* Odisha
* Puducherry
* Punjab
* Rajasthan
* Sikkim
* Tamil Nadu
* Telangana
* Tripura
* Uttar Pradesh
* Uttarakhand
* West Bengal

### Primary Sources for Old Policies {.prim-source}
* Andaman and Nicobar
* Andhra Pradesh
* Arunachal Pradesh
* Assam
* Bihar
* Chandigarh
* Chhattisgarh
* Dadra and Nagar Haveli
* Daman and Diu
* Delhi
* Goa
* Gujarat
* Haryana
* Himachal Pradesh
* Jammu and Kashmir
* Jharkhand
* Karnataka
* Kerala
* Laccadives
* Ladakh
* Madhya Pradesh
* Maharashtra
* Manipur
* Meghalaya
* Mizoram
* Nagaland
* Odisha
* Puducherry
* Punjab
* Rajasthan
* Sikkim
* Tamil Nadu
* Telangana
* Tripura
* Uttar Pradesh
* Uttarakhand
* West Bengal

France {data-navmenu="Country Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Country Managers**

* **Audrey Firrone**
* **Emily Westropp**

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------

### General Country Information {.gen-country}

* Auvergne-Rhone-Alpes
* Bourgogne-Franche-Comte
* Brittany
* Centre
* Corsica
* Grand Est
* Hauts-de-France
* Ile-de-France
* Normandy
* Nouvelle-Aquitaine
* Occitanie
* Pays de la Loire
* Provence-Alpes-Cote d'Azur
* French Guiana
* Guadeloupe
* Martinique
* Mayotte
* Reunion

Row
-------------------------------------
### RA Materials { .prev-ra }
* Auvergne-Rhone-Alpes
* Bourgogne-Franche-Comte
* Brittany
* Centre
* Corsica
* Grand Est
* Hauts-de-France
* Ile-de-France
* Normandy
* Nouvelle-Aquitaine
* Occitanie
* Pays de la Loire
* Provence-Alpes-Cote d'Azur
* French Guiana
* Guadeloupe
* Martinique
* Mayotte
* Reunion

### Primary Sources for Old Policies {.prim-source}
* Auvergne-Rhone-Alpes
* Bourgogne-Franche-Comte
* Brittany
* Centre
* Corsica
* Grand Est
* Hauts-de-France
* Ile-de-France
* Normandy
* Nouvelle-Aquitaine
* Occitanie
* Pays de la Loire
* Provence-Alpes-Cote d'Azur
* French Guiana
* Guadeloupe
* Martinique
* Mayotte
* Reunion

United States {data-navmenu="Country Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Country Managers**

* **Derek Duba**
* **Matthew Cottrell**

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------

### General Country Information {.gen-country}

* Alabama
* Alaska
* Arizona
* Arkansas
* California
* Colorado
* Connecticut
* Delaware
* Florida
* Georgia
* Hawaii
* Idaho
* Illinois
* Indiana
* Iowa
* Kansas
* Kentucky
* Louisiana
* Maine
* Maryland
* Massachusetts
* Michigan
* Minnesota
* Mississippi
* Missouri
* Montana
* Nebraska
* Nevada
* New Hampshire
* New Jersey
* New Mexico
* New York
* North Carolina
* North Dakota
* Ohio
* Oklahoma
* Oregon
* Pennsylvania
* Rhode Island
* South Carolina
* South Dakota
* Tennessee
* Texas
* Utah
* Vermont
* Virginia
* Washington
* Washington, D.C.
* West Virginia
* Wisconsin
* Wyoming
* Puerto Rico

Row
-------------------------------------
### RA Materials { .prev-ra }
* Alabama
* Alaska
* Arizona
* Arkansas
* California
* Colorado
* Connecticut
* Delaware
* Florida
* Georgia
* Hawaii
* Idaho
* Illinois
* Indiana
* Iowa
* Kansas
* Kentucky
* Louisiana
* Maine
* Maryland
* Massachusetts
* Michigan
* Minnesota
* Mississippi
* Missouri
* Montana
* Nebraska
* Nevada
* New Hampshire
* New Jersey
* New Mexico
* New York
* North Carolina
* North Dakota
* Ohio
* Oklahoma
* Oregon
* Pennsylvania
* Rhode Island
* South Carolina
* South Dakota
* Tennessee
* Texas
* Utah
* Vermont
* Virginia
* Washington
* Washington, D.C.
* West Virginia
* Wisconsin
* Wyoming
* Puerto Rico

### Primary Sources for Old Policies {.prim-source}
* Alabama
* Alaska
* Arizona
* Arkansas
* California
* Colorado
* Connecticut
* Delaware
* Florida
* Georgia
* Hawaii
* Idaho
* Illinois
* Indiana
* Iowa
* Kansas
* Kentucky
* Louisiana
* Maine
* Maryland
* Massachusetts
* Michigan
* Minnesota
* Mississippi
* Missouri
* Montana
* Nebraska
* Nevada
* New Hampshire
* New Jersey
* New Mexico
* New York
* North Carolina
* North Dakota
* Ohio
* Oklahoma
* Oregon
* Pennsylvania
* Rhode Island
* South Carolina
* South Dakota
* Tennessee
* Texas
* Utah
* Vermont
* Virginia
* Washington
* Washington, D.C.
* West Virginia
* Wisconsin
* Wyoming
* Puerto Rico

Germany {data-navmenu="Country Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Country Manager**

* **Katrin Hermann**

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------

### General Country Information {.gen-country}

* Baden-Wuerttemberg
* Bavaria
* Berlin
* Brandenburg
* Bremen
* Hamburg
* Hesse
* Lower Saxony
* Mecklenburg-Vorpommern
* North Rhine-Westphalia
* Rheinland-Pfalz
* Saarland
* Saxony
* Saxony-Anhalt
* Schleswig-Holstein
* Thuringia

Row
-------------------------------------
### RA Materials { .prev-ra }
* Baden-Wuerttemberg
* Bavaria
* Berlin
* Brandenburg
* Bremen
* Hamburg
* Hesse
* Lower Saxony
* Mecklenburg-Vorpommern
* North Rhine-Westphalia
* Rheinland-Pfalz
* Saarland
* Saxony
* Saxony-Anhalt
* Schleswig-Holstein
* Thuringia

### Primary Sources for Old Policies {.prim-source}
* Baden-Wuerttemberg
* Bavaria
* Berlin
* Brandenburg
* Bremen
* Hamburg
* Hesse
* Lower Saxony
* Mecklenburg-Vorpommern
* North Rhine-Westphalia
* Rheinland-Pfalz
* Saarland
* Saxony
* Saxony-Anhalt
* Schleswig-Holstein
* Thuringia

Japan {data-navmenu="Country Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Country Manager**

* **Victoria Atanasov**

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------

### General Country Information {.gen-country}

* Aichi
* Akita
* Aomori
* Chiba
* Ehime
* Fukui
* Fukuoka
* Fukushima
* Gifu
* Gunma
* Hiroshima
* Hokkaido
* Hyogo
* Ibaraki
* Ishikawa
* Iwate
* Kagawa
* Kagoshima
* Kanagawa
* Kochi
* Kumamoto
* Kyoto
* Mie
* Miyagi
* Miyazaki
* Nagano
* Nagasaki
* Nara
* Niigata
* Oita
* Okayama
* Okinawa
* Osaka
* Saga
* Saitama
* Shiga
* Shimane
* Shizuoka
* Tochigi
* Tokushima
* Tokyo
* Tottori
* Toyama
* Wakayama
* Yamagata
* Yamaguchi
* Yamanashi

Row
-------------------------------------
### RA Materials { .prev-ra }
* Aichi
* Akita
* Aomori
* Chiba
* Ehime
* Fukui
* Fukuoka
* Fukushima
* Gifu
* Gunma
* Hiroshima
* Hokkaido
* Hyogo
* Ibaraki
* Ishikawa
* Iwate
* Kagawa
* Kagoshima
* Kanagawa
* Kochi
* Kumamoto
* Kyoto
* Mie
* Miyagi
* Miyazaki
* Nagano
* Nagasaki
* Nara
* Niigata
* Oita
* Okayama
* Okinawa
* Osaka
* Saga
* Saitama
* Shiga
* Shimane
* Shizuoka
* Tochigi
* Tokushima
* Tokyo
* Tottori
* Toyama
* Wakayama
* Yamagata
* Yamaguchi
* Yamanashi

### Primary Sources for Old Policies {.prim-source}
* Aichi
* Akita
* Aomori
* Chiba
* Ehime
* Fukui
* Fukuoka
* Fukushima
* Gifu
* Gunma
* Hiroshima
* Hokkaido
* Hyogo
* Ibaraki
* Ishikawa
* Iwate
* Kagawa
* Kagoshima
* Kanagawa
* Kochi
* Kumamoto
* Kyoto
* Mie
* Miyagi
* Miyazaki
* Nagano
* Nagasaki
* Nara
* Niigata
* Oita
* Okayama
* Okinawa
* Osaka
* Saga
* Saitama
* Shiga
* Shimane
* Shizuoka
* Tochigi
* Tokushima
* Tokyo
* Tottori
* Toyama
* Wakayama
* Yamagata
* Yamaguchi
* Yamanashi

Switzerland {data-navmenu="Country Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Country Manager**

* **Anke Horn**

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------

### General Country Information {.gen-country}

* Aargau
* Appenzell Ausserrhoden
* Appenzell Innerrhoden
* Basel-City
* Basel-Landschaft
* Bern
* Fribourg
* Geneva
* Glarus
* Grisons
* Jura
* Lucerne
* Neuchatel
* Nidwalden
* Obwalden
* Saint Gallen
* Schaffhausen
* Schwyz
* Solothurn
* Thurgau
* Ticino
* Uri
* Valais
* Vaud
* Zug
* Zurich

Row
-------------------------------------
### RA Materials { .prev-ra }
* Aargau
* Appenzell Ausserrhoden
* Appenzell Innerrhoden
* Basel-City
* Basel-Landschaft
* Bern
* Fribourg
* Geneva
* Glarus
* Grisons
* Jura
* Lucerne
* Neuchatel
* Nidwalden
* Obwalden
* Saint Gallen
* Schaffhausen
* Schwyz
* Solothurn
* Thurgau
* Ticino
* Uri
* Valais
* Vaud
* Zug
* Zurich

### Primary Sources for Old Policies {.prim-source}
* Aargau
* Appenzell Ausserrhoden
* Appenzell Innerrhoden
* Basel-City
* Basel-Landschaft
* Bern
* Fribourg
* Geneva
* Glarus
* Grisons
* Jura
* Lucerne
* Neuchatel
* Nidwalden
* Obwalden
* Saint Gallen
* Schaffhausen
* Schwyz
* Solothurn
* Thurgau
* Ticino
* Uri
* Valais
* Vaud
* Zug
* Zurich

China {data-navmenu="Country Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Country Managers**

* **Linlin Chen**
* **Shiyu Guo**

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------

### General Country Information {.gen-country}

* Anhui
* Beijing
* Chongqing
* Fujian
* Gansu
* Guangdong
* Guangxi
* Guizhou
* Hainan
* Hebei
* Heilongjiang
* Henan
* Hubei
* Hunan
* Inner Mongolia
* Jiangsu
* Jiangxi
* Jilin
* Liaoning
* Ningxia Hui Autonomous Region
* Qinghai
* Shaanxi
* Shandong
* Shanghai
* Shanxi
* Sichuan
* Tianjin
* Tibet
* Xinjiang
* Yunnan
* Zhejiang

Row
-------------------------------------
### RA Materials { .prev-ra }
* Anhui
* Beijing
* Chongqing
* Fujian
* Gansu
* Guangdong
* Guangxi
* Guizhou
* Hainan
* Hebei
* Heilongjiang
* Henan
* Hubei
* Hunan
* Inner Mongolia
* Jiangsu
* Jiangxi
* Jilin
* Liaoning
* Ningxia Hui Autonomous Region
* Qinghai
* Shaanxi
* Shandong
* Shanghai
* Shanxi
* Sichuan
* Tianjin
* Tibet
* Xinjiang
* Yunnan
* Zhejiang

### Primary Sources for Old Policies {.prim-source}
* Anhui
* Beijing
* Chongqing
* Fujian
* Gansu
* Guangdong
* Guangxi
* Guizhou
* Hainan
* Hebei
* Heilongjiang
* Henan
* Hubei
* Hunan
* Inner Mongolia
* Jiangsu
* Jiangxi
* Jilin
* Liaoning
* Ningxia Hui Autonomous Region
* Qinghai
* Shaanxi
* Shandong
* Shanghai
* Shanxi
* Sichuan
* Tianjin
* Tibet
* Xinjiang
* Yunnan
* Zhejiang

Nigeria {data-navmenu="Country Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Country Manager**

* **Annika Kaiser**

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------

### General Country Information {.gen-country}

* Abia
* Adamawa
* Akwa Ibom
* Anambra
* Bauchi
* Bayelsa
* Benue
* Borno
* Cross River
* Delta
* Ebonyi
* Edo
* Ekiti
* Enugu
* FCT
* Gombe
* Imo
* Jigawa
* Kaduna
* Kano
* Katsina
* Kebbi
* Kogi
* Kwara
* Lagos
* Nassarawa
* Niger
* Ogun
* Ondo
* Osun
* Oyo
* Plateau
* Rivers
* Sokoto
* Taraba
* Yobe
* Zamfara

Row
-------------------------------------
### RA Materials { .prev-ra }
* Abia
* Adamawa
* Akwa Ibom
* Anambra
* Bauchi
* Bayelsa
* Benue
* Borno
* Cross River
* Delta
* Ebonyi
* Edo
* Ekiti
* Enugu
* FCT
* Gombe
* Imo
* Jigawa
* Kaduna
* Kano
* Katsina
* Kebbi
* Kogi
* Kwara
* Lagos
* Nassarawa
* Niger
* Ogun
* Ondo
* Osun
* Oyo
* Plateau
* Rivers
* Sokoto
* Taraba
* Yobe
* Zamfara

### Primary Sources for Old Policies {.prim-source}
* Abia
* Adamawa
* Akwa Ibom
* Anambra
* Bauchi
* Bayelsa
* Benue
* Borno
* Cross River
* Delta
* Ebonyi
* Edo
* Ekiti
* Enugu
* FCT
* Gombe
* Imo
* Jigawa
* Kaduna
* Kano
* Katsina
* Kebbi
* Kogi
* Kwara
* Lagos
* Nassarawa
* Niger
* Ogun
* Ondo
* Osun
* Oyo
* Plateau
* Rivers
* Sokoto
* Taraba
* Yobe
* Zamfara

Russia {data-navmenu="Country Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Country Managers**

* **Natalia Filkina-Spreizer**
* **Anelia Petrova**
* **Natalia Baratashvili**

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------

### General Country Information {.gen-country}

* Adygeya Republic
* Altai
* Altai Krai
* Amur Oblast
* Arkhangelskaya
* Astrakhan
* Bashkortostan Republic
* Belgorod Oblast
* Bryansk Oblast
* Buryatiya Republic
* Chechnya
* Chelyabinsk
* Chukotka
* Chuvashia
* Dagestan
* Ingushetiya Republic
* Irkutsk Oblast
* Ivanovo
* Jaroslavl
* Jewish Autonomous Oblast
* Kabardino-Balkariya Republic
* Kaliningrad
* Kalmykiya Republic
* Kaluga
* Kamchatka
* Karachayevo-Cherkesiya Republic
* Karelia
* Kemerovo Oblast
* Khabarovsk
* Khakasiya Republic
* Khanty-Mansia
* Kirov
* Komi
* Kostroma Oblast
* Krasnodarskiy
* Krasnoyarskiy
* Kurgan Oblast
* Kursk
* Leningradskaya Oblast'
* Lipetsk Oblast
* Magadan Oblast
* Mariy-El Republic
* Mordoviya Republic
* Moscow
* Moscow Oblast
* Murmansk
* Nenets
* Nizhny Novgorod Oblast
* North Ossetia
* Novgorod Oblast
* Novosibirsk Oblast
* Omsk
* Orel Oblast
* Orenburg Oblast
* Penza
* Perm
* Primorskiy (Maritime) Kray
* Pskov Oblast
* Republic of Tyva
* Rostov
* Ryazan Oblast
* Sakha
* Sakhalin Oblast
* Samara Oblast
* Saratovskaya Oblast
* Smolensk
* St.-Petersburg
* Stavropol' Kray
* Sverdlovsk
* Tambov
* Tatarstan Republic
* Tomsk Oblast
* Transbaikal Territory
* Tula
* Tver' Oblast
* Tyumen' Oblast
* Udmurtiya Republic
* Ulyanovsk
* Vladimir
* Volgograd Oblast
* Vologda
* Voronezj
* Yamalo-Nenets
* Crimea
* Sevastopol

Row
-------------------------------------
### RA Materials { .prev-ra }
* Adygeya Republic
* Altai
* Altai Krai
* Amur Oblast
* Arkhangelskaya
* Astrakhan
* Bashkortostan Republic
* Belgorod Oblast
* Bryansk Oblast
* Buryatiya Republic
* Chechnya
* Chelyabinsk
* Chukotka
* Chuvashia
* Dagestan
* Ingushetiya Republic
* Irkutsk Oblast
* Ivanovo
* Jaroslavl
* Jewish Autonomous Oblast
* Kabardino-Balkariya Republic
* Kaliningrad
* Kalmykiya Republic
* Kaluga
* Kamchatka
* Karachayevo-Cherkesiya Republic
* Karelia
* Kemerovo Oblast
* Khabarovsk
* Khakasiya Republic
* Khanty-Mansia
* Kirov
* Komi
* Kostroma Oblast
* Krasnodarskiy
* Krasnoyarskiy
* Kurgan Oblast
* Kursk
* Leningradskaya Oblast'
* Lipetsk Oblast
* Magadan Oblast
* Mariy-El Republic
* Mordoviya Republic
* Moscow
* Moscow Oblast
* Murmansk
* Nenets
* Nizhny Novgorod Oblast
* North Ossetia
* Novgorod Oblast
* Novosibirsk Oblast
* Omsk
* Orel Oblast
* Orenburg Oblast
* Penza
* Perm
* Primorskiy (Maritime) Kray
* Pskov Oblast
* Republic of Tyva
* Rostov
* Ryazan Oblast
* Sakha
* Sakhalin Oblast
* Samara Oblast
* Saratovskaya Oblast
* Smolensk
* St.-Petersburg
* Stavropol' Kray
* Sverdlovsk
* Tambov
* Tatarstan Republic
* Tomsk Oblast
* Transbaikal Territory
* Tula
* Tver' Oblast
* Tyumen' Oblast
* Udmurtiya Republic
* Ulyanovsk
* Vladimir
* Volgograd Oblast
* Vologda
* Voronezj
* Yamalo-Nenets
* Crimea
* Sevastopol

### Primary Sources for Old Policies {.prim-source}
* Adygeya Republic
* Altai
* Altai Krai
* Amur Oblast
* Arkhangelskaya
* Astrakhan
* Bashkortostan Republic
* Belgorod Oblast
* Bryansk Oblast
* Buryatiya Republic
* Chechnya
* Chelyabinsk
* Chukotka
* Chuvashia
* Dagestan
* Ingushetiya Republic
* Irkutsk Oblast
* Ivanovo
* Jaroslavl
* Jewish Autonomous Oblast
* Kabardino-Balkariya Republic
* Kaliningrad
* Kalmykiya Republic
* Kaluga
* Kamchatka
* Karachayevo-Cherkesiya Republic
* Karelia
* Kemerovo Oblast
* Khabarovsk
* Khakasiya Republic
* Khanty-Mansia
* Kirov
* Komi
* Kostroma Oblast
* Krasnodarskiy
* Krasnoyarskiy
* Kurgan Oblast
* Kursk
* Leningradskaya Oblast'
* Lipetsk Oblast
* Magadan Oblast
* Mariy-El Republic
* Mordoviya Republic
* Moscow
* Moscow Oblast
* Murmansk
* Nenets
* Nizhny Novgorod Oblast
* North Ossetia
* Novgorod Oblast
* Novosibirsk Oblast
* Omsk
* Orel Oblast
* Orenburg Oblast
* Penza
* Perm
* Primorskiy (Maritime) Kray
* Pskov Oblast
* Republic of Tyva
* Rostov
* Ryazan Oblast
* Sakha
* Sakhalin Oblast
* Samara Oblast
* Saratovskaya Oblast
* Smolensk
* St.-Petersburg
* Stavropol' Kray
* Sverdlovsk
* Tambov
* Tatarstan Republic
* Tomsk Oblast
* Transbaikal Territory
* Tula
* Tver' Oblast
* Tyumen' Oblast
* Udmurtiya Republic
* Ulyanovsk
* Vladimir
* Volgograd Oblast
* Vologda
* Voronezj
* Yamalo-Nenets
* Crimea
* Sevastopol

Spain {data-navmenu="Country Dashboards"}
=====================================

Inputs {.sidebar}
-------------------------------------
**Country Manager**

* **Ana Belén Perianes**

 <br> 
 <details> 

 <summary> <small> <p style="color:blue">How to access RA Materials </p></summary> </small> 
 <small> 

 1. Create a [github](https://github.com) account and username 
 2. Request access to this repository [here](https://docs.google.com/spreadsheets/d/1zQvNOSFAfPmlZ0lANaskJ4z05wL1HVUIbC9ZFkeuHYs/edit?usp=sharing) </small> 
 </details>

Row
-------------------------------------

### General Country Information {.gen-country}

* Andalusia
* Aragon
* Asturias
* Balearic Islands
* Basque Country
* Canary Islands
* Cantabria
* Castille and Leon
* Castille-La Mancha
* Catalonia
* Ceuta
* Extremadura
* Galicia
* La Rioja
* Madrid
* Melilla
* Murcia
* Navarre
* Valencia

Row
-------------------------------------
### RA Materials { .prev-ra }
* Andalusia
* Aragon
* Asturias
* Balearic Islands
* Basque Country
* Canary Islands
* Cantabria
* Castille and Leon
* Castille-La Mancha
* Catalonia
* Ceuta
* Extremadura
* Galicia
* La Rioja
* Madrid
* Melilla
* Murcia
* Navarre
* Valencia

### Primary Sources for Old Policies {.prim-source}
* Andalusia
* Aragon
* Asturias
* Balearic Islands
* Basque Country
* Canary Islands
* Cantabria
* Castille and Leon
* Castille-La Mancha
* Catalonia
* Ceuta
* Extremadura
* Galicia
* La Rioja
* Madrid
* Melilla
* Murcia
* Navarre
* Valencia

